let cidades = [
  "Rio Branco",
  "Cruzeiro do Sul",
  "Sena Madureira",
  "Tarauacá",
  "Feijó",
  "Brasiléia",
  "Senador Guiomard",
  "Plácido de Castro",
  "Xapuri",
  "Rodrigues Alves",
  "Marechal Thaumaturgo",
  "Mâncio Lima",
  "Porto Acre",
  "Epitaciolândia",
  "Acrelândia",
  "Porto Walter",
  "Capixaba",
  "Bujari",
  "Manoel Urbano",
  "Jordão",
  "Assis Brasil",
  "Santa Rosa do Purus",
  "Maceió",
  "Arapiraca",
  "Rio Largo",
  "Palmeira dos Índios",
  "União dos Palmares",
  "Penedo",
  "São Miguel dos Campos",
  "Campo Alegre",
  "Coruripe",
  "Marechal Deodoro",
  "Delmiro Gouveia",
  "Santana do Ipanema",
  "Atalaia",
  "Teotônio Vilela",
  "Girau do Ponciano",
  "Pilar",
  "São Luís do Quitunde",
  "São Sebastião",
  "Maragogi",
  "São José da Tapera",
  "Limoeiro de Anadia",
  "Murici",
  "Traipu",
  "Boca da Mata",
  "Porto Calvo",
  "Viçosa",
  "Igaci",
  "Piranhas",
  "Mata Grande",
  "Junqueiro",
  "Igreja Nova",
  "Matriz de Camaragibe",
  "Craíbas",
  "Pão de Açúcar",
  "Joaquim Gomes",
  "São José da Laje",
  "Feira Grande",
  "Colônia Leopoldina",
  "Olho d'Água das Flores",
  "Cajueiro",
  "Água Branca",
  "Taquarana",
  "Porto Real do Colégio",
  "Major Izidoro",
  "Batalha",
  "Inhapi",
  "Estrela de Alagoas",
  "Messias",
  "Piaçabuçu",
  "Canapi",
  "Lagoa da Canoa",
  "Anadia",
  "Capela",
  "Barra de Santo Antônio",
  "Ibateguara",
  "Passo de Camaragibe",
  "Poço das Trincheiras",
  "Satuba",
  "Senador Rui Palmeira",
  "Paripueira",
  "Maribondo",
  "Novo Lino",
  "Flexeiras",
  "Olivença",
  "Ouro Branco",
  "Jequiá da Praia",
  "Quebrangulo",
  "Dois Riachos",
  "Cacimbinhas",
  "Santana do Mundaú",
  "Coité do Noia",
  "Pariconha",
  "Branquinha",
  "Campo Grande",
  "Carneiros",
  "Olho d'Água do Casado",
  "Maravilha",
  "Japaratinga",
  "Barra de São Miguel",
  "São Miguel dos Milagres",
  "Porto de Pedras",
  "Paulo Jacinto",
  "Santa Luzia do Norte",
  "Chã Preta",
  "Monteirópolis",
  "Jacuípe",
  "São Brás",
  "Campestre",
  "Belo Monte",
  "Roteiro",
  "Tanque d'Arca",
  "Coqueiro Seco",
  "Jaramataia",
  "Minador do Negrão",
  "Jacaré dos Homens",
  "Olho d'Água Grande",
  "Palestina",
  "Feliz Deserto",
  "Belém",
  "Jundiá",
  "Mar Vermelho",
  "Pindoba",
  "Macapá",
  "Santana",
  "Laranjal do Jari",
  "Oiapoque",
  "Porto Grande",
  "Mazagão",
  "Tartarugalzinho",
  "Pedra Branca do Amapari",
  "Vitória do Jari",
  "Calçoene",
  "Amapá",
  "Ferreira Gomes",
  "Cutias",
  "Itaubal",
  "Serra do Navio",
  "Pracuúba",
  "Manaus",
  "Itacoatiara",
  "Manacapuru",
  "Parintins",
  "Coari",
  "Tabatinga",
  "Maués",
  "Tefé",
  "Manicoré",
  "Humaitá",
  "Iranduba",
  "Lábrea",
  "São Gabriel da Cachoeira",
  "Benjamin Constant",
  "Borba",
  "Autazes",
  "São Paulo de Olivença",
  "Careiro",
  "Nova Olinda do Norte",
  "Presidente Figueiredo",
  "Eirunepé",
  "Boca do Acre",
  "Rio Preto da Eva",
  "Manaquiri",
  "Barreirinha",
  "Careiro da Várzea",
  "Ipixuna",
  "Codajás",
  "Carauari",
  "Barcelos",
  "Santa Isabel do Rio Negro",
  "Novo Aripuanã",
  "Urucurituba",
  "Apuí",
  "Anori",
  "Nhamundá",
  "Santo Antônio do Içá",
  "Atalaia do Norte",
  "Envira",
  "Beruri",
  "Novo Airão",
  "Boa Vista do Ramos",
  "Pauini",
  "Tonantins",
  "Maraã",
  "Guajará",
  "Tapauá",
  "Fonte Boa",
  "Alvarães",
  "Urucará",
  "Canutama",
  "Juruá",
  "São Sebastião do Uatumã",
  "Anamã",
  "Uarini",
  "Caapiranga",
  "Jutaí",
  "Amaturá",
  "Itapiranga",
  "Silves",
  "Itamarati",
  "Japurá",
  "Salvador",
  "Feira de Santana",
  "Vitória da Conquista",
  "Camaçari",
  "Juazeiro",
  "Lauro de Freitas",
  "Itabuna",
  "Ilhéus",
  "Porto Seguro",
  "Barreiras",
  "Jequié",
  "Alagoinhas",
  "Teixeira de Freitas",
  "Simões Filho",
  "Eunápolis",
  "Paulo Afonso",
  "Santo Antônio de Jesus",
  "Valença",
  "Luís Eduardo Magalhães",
  "Candeias",
  "Guanambi",
  "Dias d'Ávila",
  "Serrinha",
  "Jacobina",
  "Senhor do Bonfim",
  "Itapetinga",
  "Irecê",
  "Casa Nova",
  "Campo Formoso",
  "Bom Jesus da Lapa",
  "Brumado",
  "Conceição do Coité",
  "Itaberaba",
  "Itamaraju",
  "Cruz das Almas",
  "Euclides da Cunha",
  "Santo Amaro",
  "Ipirá",
  "Catu",
  "Jaguaquara",
  "Araci",
  "Barra",
  "Ribeira do Pombal",
  "Santo Estêvão",
  "Caetité",
  "Tucano",
  "Macaúbas",
  "Monte Santo",
  "Mata de São João",
  "Poções",
  "Xique-Xique",
  "Livramento de Nossa Senhora",
  "Ipiaú",
  "Maragogipe",
  "São Sebastião do Passé",
  "Seabra",
  "Vera Cruz",
  "Nova Viçosa",
  "Mucuri",
  "Entre Rios",
  "Remanso",
  "Sento Sé",
  "Rio Real",
  "Jeremoabo",
  "Inhambupe",
  "São Francisco do Conde",
  "Pojuca",
  "Santa Maria da Vitória",
  "São Gonçalo dos Campos",
  "Esplanada",
  "Santaluz",
  "Amargosa",
  "Itapicuru",
  "Itiúba",
  "Riacho de Santana",
  "Morro do Chapéu",
  "Camamu",
  "Pilão Arcado",
  "Curaçá",
  "Cansanção",
  "São Desidério",
  "Jaguarari",
  "Cachoeira",
  "Conceição do Jacuípe",
  "Riachão do Jacuípe",
  "Gandu",
  "Cícero Dantas",
  "Paratinga",
  "Correntina",
  "Camacan",
  "Serra do Ramalho",
  "Capim Grosso",
  "Itabela",
  "Ruy Barbosa",
  "Barra do Choça",
  "Canavieiras",
  "Muritiba",
  "Irará",
  "Paripiranga",
  "Carinhanha",
  "Valente",
  "Itacaré",
  "Ituberá",
  "Campo Alegre de Lourdes",
  "Nazaré",
  "Santa Rita de Cássia",
  "Olindina",
  "Presidente Tancredo Neves",
  "Prado",
  "Santa Cruz Cabrália",
  "Quijingue",
  "Ubatã",
  "Lapão",
  "Mundo Novo",
  "Ibotirama",
  "Nova Soure",
  "Iguaí",
  "Santana",
  "Planalto",
  "Canarana",
  "Castro Alves",
  "Conde",
  "Formosa do Rio Preto",
  "Miguel Calmon",
  "Iraquara",
  "João Dourado",
  "Queimadas",
  "Piritiba",
  "Amélia Rodrigues",
  "Cândido Sales",
  "Laje",
  "Uauá",
  "Iaçu",
  "Belmonte",
  "Ibirapitanga",
  "Caculé",
  "Sobradinho",
  "Conceição da Feira",
  "Medeiros Neto",
  "Rafael Jambeiro",
  "Teofilândia",
  "Alcobaça",
  "Itambé",
  "Itaparica",
  "Coração de Maria",
  "Mutuípe",
  "Riachão das Neves",
  "Caravelas",
  "Palmas de Monte Alto",
  "Oliveira dos Brejinhos",
  "Paramirim",
  "Madre de Deus",
  "Boquira",
  "Taperoá",
  "Buritirama",
  "Anagé",
  "Crisópolis",
  "Ibicaraí",
  "São Felipe",
  "Santa Bárbara",
  "Wenceslau Guimarães",
  "Governador Mangabeira",
  "Maraú",
  "Abaré",
  "Guaratinga",
  "Baixa Grande",
  "Itororó",
  "Tanhaçu",
  "Uruçuca",
  "Itajuípe",
  "Barra da Estiva",
  "Pindobaçu",
  "Ibicoara",
  "Maracás",
  "Itarantim",
  "Ubaíra",
  "Antas",
  "Umburanas",
  "Utinga",
  "Itanhém",
  "Jaguaripe",
  "Ituaçu",
  "Macarani",
  "Cabaceiras do Paraguaçu",
  "Cocos",
  "São Gabriel",
  "Cairu",
  "Ubaitaba",
  "Mirangaba",
  "Cafarnaum",
  "Mairi",
  "Boa Vista do Tupim",
  "Ibipeba",
  "Buerarema",
  "Una",
  "Aporá",
  "Fátima",
  "Ourolândia",
  "Tanque Novo",
  "Sapeaçu",
  "Cipó",
  "Sátiro Dias",
  "Central",
  "Serra Dourada",
  "Adustina",
  "Souto Soares",
  "Condeúba",
  "Água Fria",
  "Conceição do Almeida",
  "Ibititá",
  "Belo Campo",
  "Bonito",
  "Tapiramutá",
  "Malhada",
  "Piatã",
  "Canudos",
  "Pedro Alexandre",
  "Urandi",
  "Nova Canaã",
  "Ibitiara",
  "Filadélfia",
  "Pindaí",
  "Ibicuí",
  "Barrocas",
  "Itaetê",
  "Coaraci",
  "América Dourada",
  "Salinas da Margarida",
  "Tremedal",
  "Biritinga",
  "Encruzilhada",
  "Lagoa Real",
  "Igaporã",
  "Coronel João Sá",
  "São Félix do Coribe",
  "Rio do Antônio",
  "Novo Triunfo",
  "Glória",
  "Jussara",
  "Acajutiba",
  "Presidente Dutra",
  "Barro Alto",
  "Teolândia",
  "Ibipitanga",
  "Jacaraci",
  "São Félix",
  "Ponto Novo",
  "Caetanos",
  "Itaguaçu da Bahia",
  "Ribeira do Amparo",
  "Itatim",
  "Retirolândia",
  "Jiquiriçá",
  "Serra Preta",
  "Boninal",
  "Ibirataia",
  "Andorinha",
  "Candiba",
  "Itagibá",
  "Ipecaetá",
  "Nilo Peçanha",
  "Brejões",
  "Várzea da Roça",
  "Coribe",
  "Cristópolis",
  "Baianópolis",
  "Santa Brígida",
  "Angical",
  "Uibaí",
  "Mansidão",
  "Cotegipe",
  "Mascote",
  "Pé de Serra",
  "Serrolândia",
  "Caldeirão Grande",
  "Banzaê",
  "Nordestina",
  "Barra do Mendes",
  "Andaraí",
  "Sítio do Mato",
  "Terra Nova",
  "Saúde",
  "Igrapiúna",
  "Aracatu",
  "Heliópolis",
  "Manoel Vitorino",
  "Rio de Contas",
  "Novo Horizonte",
  "Várzea Nova",
  "Tabocas do Brejo Velho",
  "Itiruçu",
  "Matina",
  "Licínio de Almeida",
  "Santa Luzia",
  "Dom Basílio",
  "Araçás",
  "Saubara",
  "Itagi",
  "Wanderley",
  "Mortugaba",
  "Boa Nova",
  "Presidente Jânio Quadros",
  "Antônio Gonçalves",
  "São Miguel das Matas",
  "Rio do Pires",
  "Antônio Cardoso",
  "Capela do Alto Alegre",
  "Lençóis",
  "Sebastião Laranjeiras",
  "Aramari",
  "Muquém do São Francisco",
  "Anguera",
  "Macajuba",
  "Gentio do Ouro",
  "Chorrochó",
  "Aurelino Leal",
  "Iuiú",
  "Arataca",
  "Milagres",
  "Jandaíra",
  "Brotas de Macaúbas",
  "Brejolândia",
  "Santa Inês",
  "São José do Jacuípe",
  "Floresta Azul",
  "Santa Teresinha",
  "Érico Cardoso",
  "Jitaúna",
  "Mulungu do Morro",
  "Marcionílio Souza",
  "Pintadas",
  "Dário Meira",
  "Maiquinique",
  "Itapitanga",
  "Piripá",
  "Itapebi",
  "Botuporã",
  "Piraí do Norte",
  "Ipupiara",
  "Bom Jesus da Serra",
  "Canápolis",
  "Pau Brasil",
  "Rodelas",
  "Sítio do Quinto",
  "Planaltino",
  "Cardeal da Silva",
  "Wagner",
  "Caturama",
  "Várzea do Poço",
  "Nova Redenção",
  "Palmeiras",
  "São Domingos",
  "Santanópolis",
  "Quixabeira",
  "Caém",
  "Jucuruçu",
  "Ibiassucê",
  "Aratuípe",
  "Ibirapuã",
  "Varzedo",
  "Mucugê",
  "Abaíra",
  "Cordeiros",
  "Caraíbas",
  "Lagedo do Tabocal",
  "Ouriçangas",
  "Morpará",
  "Itaquara",
  "Nova Itarana",
  "Malhada de Pedras",
  "Itapé",
  "Mirante",
  "Jaborandi",
  "Elísio Medrado",
  "Candeal",
  "Lamarão",
  "Itamari",
  "Tanquinho",
  "Iramaia",
  "Nova Fátima",
  "Macururé",
  "Muniz Ferreira",
  "Pedrão",
  "Teodoro Sampaio",
  "Irajuba",
  "Apuarema",
  "Gongogi",
  "Itagimirim",
  "Potiraguá",
  "Nova Ibiá",
  "Itaju do Colônia",
  "Itanagra",
  "Guajeru",
  "Santa Cruz da Vitória",
  "Caatiba",
  "Ichu",
  "Vereda",
  "Jussiape",
  "Jussari",
  "Feira da Mata",
  "Firmino Alves",
  "São José da Vitória",
  "Barra do Rocha",
  "Cravolândia",
  "Barro Preto",
  "Almadina",
  "Ribeirão do Largo",
  "Gavião",
  "Aiquara",
  "Dom Macedo Costa",
  "Ibiquera",
  "Contendas do Sincorá",
  "Lajedão",
  "Lajedinho",
  "Lafaiete Coutinho",
  "Catolândia",
  "Maetinga",
  "",
  "",
];

let sortedNames = cidades.sort();
let input = document.getElementById("input");
let text = document.getElementById("first-text");
let nameCity = document.getElementById("second-text");

input.addEventListener("keyup", (e) => {
  removeElements();
  for (let i of sortedNames) {

    if (
      i.toLowerCase().startsWith(input.value.toLowerCase()) &&
      input.value != ""
    ) {
      let listItem = document.createElement("li");
      listItem.classList.add("list-items");
      listItem.style.cursor = "pointer";
      listItem.setAttribute("onclick", "displayNames('" + i + "')");
      let word = "<b>" + i.substr(0, input.value.length) + "</b>";
      word += i.substr(input.value.length);
      listItem.innerHTML = word;
      document.querySelector(".list").appendChild(listItem);
      text.innerText = ""
      nameCity.innerText = ""
    }
  }
});
function displayNames(value) {
  input.value = value;
  text.innerText = "Você escolheu a cidade: "
  nameCity.innerText = input.value
  removeElements();
}

function removeElements() {
  let items = document.querySelectorAll(".list-items");
  items.forEach((item) => {
    item.remove();
  });
}
