let cidades = [
  "Rio Branco",
  "Cruzeiro do Sul",
  "Sena Madureira",
  "Tarauacá",
  "Feijó",
  "Brasiléia",
  "Senador Guiomard",
  "Plácido de Castro",
  "Xapuri",
  "Rodrigues Alves",
  "Marechal Thaumaturgo",
  "Mâncio Lima",
  "Porto Acre",
  "Epitaciolândia",
  "Acrelândia",
  "Porto Walter",
  "Capixaba",
  "Bujari",
  "Manoel Urbano",
  "Jordão",
  "Assis Brasil",
  "Santa Rosa do Purus",
  "Maceió",
  "Arapiraca",
  "Rio Largo",
  "Palmeira dos Índios",
  "União dos Palmares",
  "Penedo",
  "São Miguel dos Campos",
  "Campo Alegre",
  "Coruripe",
  "Marechal Deodoro",
  "Delmiro Gouveia",
  "Santana do Ipanema",
  "Atalaia",
  "Teotônio Vilela",
  "Girau do Ponciano",
  "Pilar",
  "São Luís do Quitunde",
  "São Sebastião",
  "Maragogi",
  "São José da Tapera",
  "Limoeiro de Anadia",
  "Murici",
  "Traipu",
  "Boca da Mata",
  "Porto Calvo",
  "Viçosa",
  "Igaci",
  "Piranhas",
  "Mata Grande",
  "Junqueiro",
  "Igreja Nova",
  "Matriz de Camaragibe",
  "Craíbas",
  "Pão de Açúcar",
  "Joaquim Gomes",
  "São José da Laje",
  "Feira Grande",
  "Colônia Leopoldina",
  "Olho d'Água das Flores",
  "Cajueiro",
  "Água Branca",
  "Taquarana",
  "Porto Real do Colégio",
  "Major Izidoro",
  "Batalha",
  "Inhapi",
  "Estrela de Alagoas",
  "Messias",
  "Piaçabuçu",
  "Canapi",
  "Lagoa da Canoa",
  "Anadia",
  "Capela",
  "Barra de Santo Antônio",
  "Ibateguara",
  "Passo de Camaragibe",
  "Poço das Trincheiras",
  "Satuba",
  "Senador Rui Palmeira",
  "Paripueira",
  "Maribondo",
  "Novo Lino",
  "Flexeiras",
  "Olivença",
  "Ouro Branco",
  "Jequiá da Praia",
  "Quebrangulo",
  "Dois Riachos",
  "Cacimbinhas",
  "Santana do Mundaú",
  "Coité do Noia",
  "Pariconha",
  "Branquinha",
  "Campo Grande",
  "Carneiros",
  "Olho d'Água do Casado",
  "Maravilha",
  "Japaratinga",
  "Barra de São Miguel",
  "São Miguel dos Milagres",
  "Porto de Pedras",
  "Paulo Jacinto",
  "Santa Luzia do Norte",
  "Chã Preta",
  "Monteirópolis",
  "Jacuípe",
  "São Brás",
  "Campestre",
  "Belo Monte",
  "Roteiro",
  "Tanque d'Arca",
  "Coqueiro Seco",
  "Jaramataia",
  "Minador do Negrão",
  "Jacaré dos Homens",
  "Olho d'Água Grande",
  "Palestina",
  "Feliz Deserto",
  "Belém",
  "Jundiá",
  "Mar Vermelho",
  "Pindoba",
  "Macapá",
  "Santana",
  "Laranjal do Jari",
  "Oiapoque",
  "Porto Grande",
  "Mazagão",
  "Tartarugalzinho",
  "Pedra Branca do Amapari",
  "Vitória do Jari",
  "Calçoene",
  "Amapá",
  "Ferreira Gomes",
  "Cutias",
  "Itaubal",
  "Serra do Navio",
  "Pracuúba",
  "Manaus",
  "Itacoatiara",
  "Manacapuru",
  "Parintins",
  "Coari",
  "Tabatinga",
  "Maués",
  "Tefé",
  "Manicoré",
  "Humaitá",
  "Iranduba",
  "Lábrea",
  "São Gabriel da Cachoeira",
  "Benjamin Constant",
  "Borba",
  "Autazes",
  "São Paulo de Olivença",
  "Careiro",
  "Nova Olinda do Norte",
  "Presidente Figueiredo",
  "Eirunepé",
  "Boca do Acre",
  "Rio Preto da Eva",
  "Manaquiri",
  "Barreirinha",
  "Careiro da Várzea",
  "Ipixuna",
  "Codajás",
  "Carauari",
  "Barcelos",
  "Santa Isabel do Rio Negro",
  "Novo Aripuanã",
  "Urucurituba",
  "Apuí",
  "Anori",
  "Nhamundá",
  "Santo Antônio do Içá",
  "Atalaia do Norte",
  "Envira",
  "Beruri",
  "Novo Airão",
  "Boa Vista do Ramos",
  "Pauini",
  "Tonantins",
  "Maraã",
  "Guajará",
  "Tapauá",
  "Fonte Boa",
  "Alvarães",
  "Urucará",
  "Canutama",
  "Juruá",
  "São Sebastião do Uatumã",
  "Anamã",
  "Uarini",
  "Caapiranga",
  "Jutaí",
  "Amaturá",
  "Itapiranga",
  "Silves",
  "Itamarati",
  "Japurá",
  "Salvador",
  "Feira de Santana",
  "Vitória da Conquista",
  "Camaçari",
  "Juazeiro",
  "Lauro de Freitas",
  "Itabuna",
  "Ilhéus",
  "Porto Seguro",
  "Barreiras",
  "Jequié",
  "Alagoinhas",
  "Teixeira de Freitas",
  "Simões Filho",
  "Eunápolis",
  "Paulo Afonso",
  "Santo Antônio de Jesus",
  "Valença",
  "Luís Eduardo Magalhães",
  "Candeias",
  "Guanambi",
  "Dias d'Ávila",
  "Serrinha",
  "Jacobina",
  "Senhor do Bonfim",
  "Itapetinga",
  "Irecê",
  "Casa Nova",
  "Campo Formoso",
  "Bom Jesus da Lapa",
  "Brumado",
  "Conceição do Coité",
  "Itaberaba",
  "Itamaraju",
  "Cruz das Almas",
  "Euclides da Cunha",
  "Santo Amaro",
  "Ipirá",
  "Catu",
  "Jaguaquara",
  "Araci",
  "Barra",
  "Ribeira do Pombal",
  "Santo Estêvão",
  "Caetité",
  "Tucano",
  "Macaúbas",
  "Monte Santo",
  "Mata de São João",
  "Poções",
  "Xique-Xique",
  "Livramento de Nossa Senhora",
  "Ipiaú",
  "Maragogipe",
  "São Sebastião do Passé",
  "Seabra",
  "Vera Cruz",
  "Nova Viçosa",
  "Mucuri",
  "Entre Rios",
  "Remanso",
  "Sento Sé",
  "Rio Real",
  "Jeremoabo",
  "Inhambupe",
  "São Francisco do Conde",
  "Pojuca",
  "Santa Maria da Vitória",
  "São Gonçalo dos Campos",
  "Esplanada",
  "Santaluz",
  "Amargosa",
  "Itapicuru",
  "Itiúba",
  "Riacho de Santana",
  "Morro do Chapéu",
  "Camamu",
  "Pilão Arcado",
  "Curaçá",
  "Cansanção",
  "São Desidério",
  "Jaguarari",
  "Cachoeira",
  "Conceição do Jacuípe",
  "Riachão do Jacuípe",
  "Gandu",
  "Cícero Dantas",
  "Paratinga",
  "Correntina",
  "Camacan",
  "Serra do Ramalho",
  "Capim Grosso",
  "Itabela",
  "Ruy Barbosa",
  "Barra do Choça",
  "Canavieiras",
  "Muritiba",
  "Irará",
  "Paripiranga",
  "Carinhanha",
  "Valente",
  "Itacaré",
  "Ituberá",
  "Campo Alegre de Lourdes",
  "Nazaré",
  "Santa Rita de Cássia",
  "Olindina",
  "Presidente Tancredo Neves",
  "Prado",
  "Santa Cruz Cabrália",
  "Quijingue",
  "Ubatã",
  "Lapão",
  "Mundo Novo",
  "Ibotirama",
  "Nova Soure",
  "Iguaí",
  "Santana",
  "Planalto",
  "Canarana",
  "Castro Alves",
  "Conde",
  "Formosa do Rio Preto",
  "Miguel Calmon",
  "Iraquara",
  "João Dourado",
  "Queimadas",
  "Piritiba",
  "Amélia Rodrigues",
  "Cândido Sales",
  "Laje",
  "Uauá",
  "Iaçu",
  "Belmonte",
  "Ibirapitanga",
  "Caculé",
  "Sobradinho",
  "Conceição da Feira",
  "Medeiros Neto",
  "Rafael Jambeiro",
  "Teofilândia",
  "Alcobaça",
  "Itambé",
  "Itaparica",
  "Coração de Maria",
  "Mutuípe",
  "Riachão das Neves",
  "Caravelas",
  "Palmas de Monte Alto",
  "Oliveira dos Brejinhos",
  "Paramirim",
  "Madre de Deus",
  "Boquira",
  "Taperoá",
  "Buritirama",
  "Anagé",
  "Crisópolis",
  "Ibicaraí",
  "São Felipe",
  "Santa Bárbara",
  "Wenceslau Guimarães",
  "Governador Mangabeira",
  "Maraú",
  "Abaré",
  "Guaratinga",
  "Baixa Grande",
  "Itororó",
  "Tanhaçu",
  "Uruçuca",
  "Itajuípe",
  "Barra da Estiva",
  "Pindobaçu",
  "Ibicoara",
  "Maracás",
  "Itarantim",
  "Ubaíra",
  "Antas",
  "Umburanas",
  "Utinga",
  "Itanhém",
  "Jaguaripe",
  "Ituaçu",
  "Macarani",
  "Cabaceiras do Paraguaçu",
  "Cocos",
  "São Gabriel",
  "Cairu",
  "Ubaitaba",
  "Mirangaba",
  "Cafarnaum",
  "Mairi",
  "Boa Vista do Tupim",
  "Ibipeba",
  "Buerarema",
  "Una",
  "Aporá",
  "Fátima",
  "Ourolândia",
  "Tanque Novo",
  "Sapeaçu",
  "Cipó",
  "Sátiro Dias",
  "Central",
  "Serra Dourada",
  "Adustina",
  "Souto Soares",
  "Condeúba",
  "Água Fria",
  "Conceição do Almeida",
  "Ibititá",
  "Belo Campo",
  "Bonito",
  "Tapiramutá",
  "Malhada",
  "Piatã",
  "Canudos",
  "Pedro Alexandre",
  "Urandi",
  "Nova Canaã",
  "Ibitiara",
  "Filadélfia",
  "Pindaí",
  "Ibicuí",
  "Barrocas",
  "Itaetê",
  "Coaraci",
  "América Dourada",
  "Salinas da Margarida",
  "Tremedal",
  "Biritinga",
  "Encruzilhada",
  "Lagoa Real",
  "Igaporã",
  "Coronel João Sá",
  "São Félix do Coribe",
  "Rio do Antônio",
  "Novo Triunfo",
  "Glória",
  "Jussara",
  "Acajutiba",
  "Presidente Dutra",
  "Barro Alto",
  "Teolândia",
  "Ibipitanga",
  "Jacaraci",
  "São Félix",
  "Ponto Novo",
  "Caetanos",
  "Itaguaçu da Bahia",
  "Ribeira do Amparo",
  "Itatim",
  "Retirolândia",
  "Jiquiriçá",
  "Serra Preta",
  "Boninal",
  "Ibirataia",
  "Andorinha",
  "Candiba",
  "Itagibá",
  "Ipecaetá",
  "Nilo Peçanha",
  "Brejões",
  "Várzea da Roça",
  "Coribe",
  "Cristópolis",
  "Baianópolis",
  "Santa Brígida",
  "Angical",
  "Uibaí",
  "Mansidão",
  "Cotegipe",
  "Mascote",
  "Pé de Serra",
  "Serrolândia",
  "Caldeirão Grande",
  "Banzaê",
  "Nordestina",
  "Barra do Mendes",
  "Andaraí",
  "Sítio do Mato",
  "Terra Nova",
  "Saúde",
  "Igrapiúna",
  "Aracatu",
  "Heliópolis",
  "Manoel Vitorino",
  "Rio de Contas",
  "Novo Horizonte",
  "Várzea Nova",
  "Tabocas do Brejo Velho",
  "Itiruçu",
  "Matina",
  "Licínio de Almeida",
  "Santa Luzia",
  "Dom Basílio",
  "Araçás",
  "Saubara",
  "Itagi",
  "Wanderley",
  "Mortugaba",
  "Boa Nova",
  "Presidente Jânio Quadros",
  "Antônio Gonçalves",
  "São Miguel das Matas",
  "Rio do Pires",
  "Antônio Cardoso",
  "Capela do Alto Alegre",
  "Lençóis",
  "Sebastião Laranjeiras",
  "Aramari",
  "Muquém do São Francisco",
  "Anguera",
  "Macajuba",
  "Gentio do Ouro",
  "Chorrochó",
  "Aurelino Leal",
  "Iuiú",
  "Arataca",
  "Milagres",
  "Jandaíra",
  "Brotas de Macaúbas",
  "Brejolândia",
  "Santa Inês",
  "São José do Jacuípe",
  "Floresta Azul",
  "Santa Teresinha",
  "Érico Cardoso",
  "Jitaúna",
  "Mulungu do Morro",
  "Marcionílio Souza",
  "Pintadas",
  "Dário Meira",
  "Maiquinique",
  "Itapitanga",
  "Piripá",
  "Itapebi",
  "Botuporã",
  "Piraí do Norte",
  "Ipupiara",
  "Bom Jesus da Serra",
  "Canápolis",
  "Pau Brasil",
  "Rodelas",
  "Sítio do Quinto",
  "Planaltino",
  "Cardeal da Silva",
  "Wagner",
  "Caturama",
  "Várzea do Poço",
  "Nova Redenção",
  "Palmeiras",
  "São Domingos",
  "Santanópolis",
  "Quixabeira",
  "Caém",
  "Jucuruçu",
  "Ibiassucê",
  "Aratuípe",
  "Ibirapuã",
  "Varzedo",
  "Mucugê",
  "Abaíra",
  "Cordeiros",
  "Caraíbas",
  "Lagedo do Tabocal",
  "Ouriçangas",
  "Morpará",
  "Itaquara",
  "Nova Itarana",
  "Malhada de Pedras",
  "Itapé",
  "Mirante",
  "Jaborandi",
  "Elísio Medrado",
  "Candeal",
  "Lamarão",
  "Itamari",
  "Tanquinho",
  "Iramaia",
  "Nova Fátima",
  "Macururé",
  "Muniz Ferreira",
  "Pedrão",
  "Teodoro Sampaio",
  "Irajuba",
  "Apuarema",
  "Gongogi",
  "Itagimirim",
  "Potiraguá",
  "Nova Ibiá",
  "Itaju do Colônia",
  "Itanagra",
  "Guajeru",
  "Santa Cruz da Vitória",
  "Caatiba",
  "Ichu",
  "Vereda",
  "Jussiape",
  "Jussari",
  "Feira da Mata",
  "Firmino Alves",
  "São José da Vitória",
  "Barra do Rocha",
  "Cravolândia",
  "Barro Preto",
  "Almadina",
  "Ribeirão do Largo",
  "Gavião",
  "Aiquara",
  "Dom Macedo Costa",
  "Ibiquera",
  "Contendas do Sincorá",
  "Lajedão",
  "Lajedinho",
  "Lafaiete Coutinho",
  "Catolândia",
  "Maetinga",
  "Fortaleza",
  "Caucaia",
  "Juazeiro do Norte",
  "Maracanaú",
  "Sobral",
  "Itapipoca",
  "Crato",
  "Maranguape",
  "Iguatu",
  "Quixadá",
  "Pacatuba",
  "Quixeramobim",
  "Aquiraz",
  "Russas",
  "Canindé",
  "Tianguá",
  "Aracati",
  "Crateús",
  "Pacajus",
  "Cascavel",
  "Horizonte",
  "Icó",
  "Camocim",
  "Acaraú",
  "Viçosa do Ceará",
  "Barbalha",
  "Morada Nova",
  "Limoeiro do Norte",
  "Tauá",
  "Trairi",
  "Granja",
  "Eusébio",
  "Acopiara",
  "Boa Viagem",
  "Beberibe",
  "Itapajé",
  "Brejo Santo",
  "São Gonçalo do Amarante",
  "Mauriti",
  "São Benedito",
  "Amontada",
  "Mombaça",
  "Santa Quitéria",
  "Pedra Branca",
  "Itarema",
  "Ipu",
  "Várzea Alegre",
  "Guaraciaba do Norte",
  "Massapê",
  "Itaitinga",
  "Ipueiras",
  "Pentecoste",
  "Baturité",
  "Missão Velha",
  "Paracuru",
  "Ubajara",
  "Jaguaribe",
  "Jaguaruana",
  "Paraipaba",
  "Bela Cruz",
  "Santana do Acaraú",
  "Nova Russas",
  "Tabuleiro do Norte",
  "Lavras da Mangabeira",
  "Parambu",
  "Redenção",
  "Novo Oriente",
  "Marco",
  "Campos Sales",
  "Milagres",
  "Jardim",
  "Caririaçu",
  "Aracoiaba",
  "Guaiúba",
  "Tamboril",
  "Independência",
  "Ocara",
  "Cedro",
  "Senador Pompeu",
  "Ibiapina",
  "Cruz",
  "Jucás",
  "Forquilha",
  "Aurora",
  "Irauçuba",
  "Assaré",
  "Coreaú",
  "Caridade",
  "Barro",
  "Morrinhos",
  "Barreira",
  "Quixeré",
  "Uruburetama",
  "Itatira",
  "Araripe",
  "Orós",
  "Quiterianópolis",
  "Catarina",
  "Pindoretama",
  "Itapiúna",
  "Jijoca de Jericoacoara",
  "Chorozinho",
  "Icapuí",
  "Hidrolândia",
  "Madalena",
  "Umirim",
  "Tejuçuoca",
  "Farias Brito",
  "Cariús",
  "Varjota",
  "Cariré",
  "Solonópole",
  "Banabuiú",
  "Reriutaba",
  "Croatá",
  "Jaguaretama",
  "Capistrano",
  "Carnaubal",
  "Santana do Cariri",
  "Aiuaba",
  "Monsenhor Tabosa",
  "Piquet Carneiro",
  "Fortim",
  "Salitre",
  "Tururu",
  "Pereiro",
  "Quixelô",
  "Alto Santo",
  "Nova Olinda",
  "Saboeiro",
  "Meruoca",
  "Acarape",
  "Barroquinha",
  "Porteiras",
  "Apuiarés",
  "Mucambo",
  "Graça",
  "Iracema",
  "Frecheirinha",
  "Uruoca",
  "Miraíma",
  "Choró",
  "Palmácia",
  "Ibaretama",
  "Milhã",
  "Chaval",
  "São Luís do Curu",
  "Ibicuitinga",
  "Ipaumirim",
  "Poranga",
  "Pacoti",
  "Paramoti",
  "Abaiara",
  "Alcântaras",
  "Aratuba",
  "Ipaporanga",
  "Jaguaribara",
  "Martinópole",
  "Groaíras",
  "Potengi",
  "Mulungu",
  "Pires Ferreira",
  "Ararendá",
  "Catunda",
  "Deputado Irapuan Pinheiro",
  "Palhano",
  "Penaforte",
  "Moraújo",
  "Tarrafas",
  "Jati",
  "Itaiçaba",
  "Arneiroz",
  "General Sampaio",
  "Senador Sá",
  "Umari",
  "Altaneira",
  "São João do Jaguaribe",
  "Antonina do Norte",
  "Ereré",
  "Pacujá",
  "Potiretama",
  "Baixio",
  "Guaramiranga",
  "Granjeiro",
  "Brasília",
  "Serra",
  "Vila Velha",
  "Cariacica",
  "Vitória",
  "Cachoeiro de Itapemirim",
  "Linhares",
  "Guarapari",
  "São Mateus",
  "Colatina",
  "Aracruz",
  "Viana",
  "Nova Venécia",
  "Barra de São Francisco",
  "Santa Maria de Jetibá",
  "Marataízes",
  "São Gabriel da Palha",
  "Castelo",
  "Itapemirim",
  "Domingos Martins",
  "Jaguaré",
  "Conceição da Barra",
  "Guaçuí",
  "Sooretama",
  "Baixo Guandu",
  "Afonso Cláudio",
  "Anchieta",
  "Alegre",
  "Iúna",
  "Pinheiros",
  "Ibatiba",
  "Pedro Canário",
  "Venda Nova do Imigrante",
  "Mimoso do Sul",
  "Santa Teresa",
  "Pancas",
  "Ecoporanga",
  "Piúma",
  "Fundão",
  "Vargem Alta",
  "Rio Bananal",
  "Montanha",
  "Muniz Freire",
  "Marechal Floriano",
  "João Neiva",
  "Mantenópolis",
  "Muqui",
  "Boa Esperança",
  "Alfredo Chaves",
  "Iconha",
  "Vila Valério",
  "Itaguaçu",
  "Irupi",
  "Marilândia",
  "Governador Lindenberg",
  "Conceição do Castelo",
  "Ibiraçu",
  "São Roque do Canaã",
  "Brejetuba",
  "Jerônimo Monteiro",
  "Atílio Vivácqua",
  "Santa Leopoldina",
  "Presidente Kennedy",
  "Rio Novo do Sul",
  "Laranja da Terra",
  "Água Doce do Norte",
  "São José do Calçado",
  "Itarana",
  "Bom Jesus do Norte",
  "Águia Branca",
  "Vila Pavão",
  "Ibitirama",
  "São Domingos do Norte",
  "Ponto Belo",
  "Alto Rio Novo",
  "Apiacá",
  "Dores do Rio Preto",
  "Mucurici",
  "Divino de São Lourenço",
  "Goiânia",
  "Aparecida de Goiânia",
  "Anápolis",
  "Rio Verde",
  "Águas Lindas de Goiás",
  "Luziânia",
  "Valparaíso de Goiás",
  "Senador Canedo",
  "Trindade",
  "Formosa",
  "Catalão",
  "Itumbiara",
  "Jataí",
  "Novo Gama",
  "Caldas Novas",
  "Planaltina",
  "Santo Antônio do Descoberto",
  "Cidade Ocidental",
  "Goianésia",
  "Mineiros",
  "Cristalina",
  "Inhumas",
  "Jaraguá",
  "Quirinópolis",
  "Niquelândia",
  "Morrinhos",
  "Goianira",
  "Porangatu",
  "Itaberaí",
  "Uruaçu",
  "Santa Helena de Goiás",
  "Posse",
  "Padre Bernardo",
  "São Luís de Montes Belos",
  "Goiatuba",
  "Pires do Rio",
  "Iporá",
  "Bela Vista de Goiás",
  "Nerópolis",
  "Palmeiras de Goiás",
  "Minaçu",
  "Alexânia",
  "Ipameri",
  "Bom Jesus de Goiás",
  "Itapuranga",
  "Pirenópolis",
  "Piracanjuba",
  "Itapaci",
  "Acreúna",
  "Hidrolândia",
  "Ceres",
  "Goiás",
  "Anicuns",
  "São Miguel do Araguaia",
  "São Simão",
  "Silvânia",
  "Abadiânia",
  "Cocalzinho de Goiás",
  "Aragarças",
  "Campos Belos",
  "Rubiataba",
  "Caiapônia",
  "Jussara",
  "Pontalina",
  "Flores de Goiás",
  "Crixás",
  "Caçu",
  "Mozarlândia",
  "Indiara",
  "Orizona",
  "Maurilândia",
  "São João d'Aliança",
  "Iaciara",
  "Guapó",
  "Vianópolis",
  "Montividiu",
  "Uruana",
  "Firminópolis",
  "São Domingos",
  "Nova Crixás",
  "Campinorte",
  "Cachoeira Alta",
  "Edéia",
  "Barro Alto",
  "Corumbá de Goiás",
  "Goianápolis",
  "Paraúna",
  "Rialma",
  "Chapadão do Céu",
  "Aragoiânia",
  "Aruanã",
  "Carmo do Rio Verde",
  "Petrolina de Goiás",
  "Paranaiguara",
  "Nova Veneza",
  "Piranhas",
  "Bonfinópolis",
  "Corumbaíba",
  "Cavalcante",
  "Buriti Alegre",
  "Nazário",
  "Mambaí",
  "Mara Rosa",
  "Abadia de Goiás",
  "Santa Rita do Araguaia",
  "Vicentinópolis",
  "Itauçu",
  "Bom Jardim de Goiás",
  "Cezarina",
  "Monte Alegre de Goiás",
  "Alvorada do Norte",
  "Serranópolis",
  "Santa Terezinha de Goiás",
  "Terezópolis de Goiás",
  "Cabeceiras",
  "Campo Limpo de Goiás",
  "Nova Glória",
  "Montes Claros de Goiás",
  "Cachoeira Dourada",
  "Campo Alegre de Goiás",
  "Araguapaz",
  "Alto Paraíso de Goiás",
  "Leopoldo de Bulhões",
  "Sanclerlândia",
  "Joviânia",
  "Itarumã",
  "Doverlândia",
  "Ouvidor",
  "Simolândia",
  "Alto Horizonte",
  "Santa Bárbara de Goiás",
  "Santo Antônio de Goiás",
  "Faina",
  "Vila Boa",
  "Inaciolândia",
  "São Francisco de Goiás",
  "Americano do Brasil",
  "Gouvelândia",
  "Jandaia",
  "Vila Propício",
  "Água Fria de Goiás",
  "Britânia",
  "Goiandira",
  "Santa Fé de Goiás",
  "Fazenda Nova",
  "Turvelândia",
  "Baliza",
  "São Luiz do Norte",
  "Itaguaru",
  "Caturaí",
  "Santo Antônio da Barra",
  "Rianápolis",
  "Rio Quente",
  "Divinópolis de Goiás",
  "Itaguari",
  "Novo Planalto",
  "Bonópolis",
  "Mundo Novo",
  "Montividiu do Norte",
  "Turvânia",
  "Itajá",
  "Itapirapuã",
  "Matrinchã",
  "Aporé",
  "Mossâmedes",
  "São Miguel do Passa-Quatro",
  "Formoso",
  "Portelândia",
  "Porteirão",
  "Gameleira de Goiás",
  "Caldazinha",
  "Amaralina",
  "Varjão",
  "Santa Isabel",
  "Brazabrantes",
  "Guarani de Goiás",
  "Mutunópolis",
  "Heitoraí",
  "Ouro Verde de Goiás",
  "Edealina",
  "Campestre de Goiás",
  "Campinaçu",
  "Palminópolis",
  "Teresina de Goiás",
  "Taquaral de Goiás",
  "Trombas",
  "Palestina de Goiás",
  "Cromínia",
  "Araçu",
  "Hidrolina",
  "Castelândia",
  "Santa Rita do Novo Destino",
  "Colinas do Sul",
  "Damianópolis",
  "Buritinópolis",
  "Estrela do Norte",
  "Professor Jamil",
  "Nova Roma",
  "Santa Tereza de Goiás",
  "Perolândia",
  "Urutaí",
  "Sítio d'Abadia",
  "Amorinópolis",
  "Aurilândia",
  "Cristianópolis",
  "Damolândia",
  "Nova Iguaçu de Goiás",
  "Ipiranga de Goiás",
  "Jaupaci",
  "Três Ranchos",
  "Uirapuru",
  "Cumari",
  "Santa Cruz de Goiás",
  "Novo Brasil",
  "Israelândia",
  "Panamá",
  "Mimoso de Goiás",
  "Adelândia",
  "Jesúpolis",
  "Diorama",
  "Aparecida do Rio Doce",
  "Buriti de Goiás",
  "Arenópolis",
  "Avelinópolis",
  "Palmelo",
  "Nova América",
  "Mairipotaba",
  "Ivolândia",
  "Marzagão",
  "Córrego do Ouro",
  "Nova Aurora",
  "Morro Agudo de Goiás",
  "Santa Rosa de Goiás",
  "Pilar de Goiás",
  "Davinópolis",
  "São Patrício",
  "Aloândia",
  "Guaraíta",
  "Água Limpa",
  "Guarinos",
  "Lagoa Santa",
  "Campos Verdes",
  "Moiporá",
  "Cachoeira de Goiás",
  "São João da Paraúna",
  "Anhanguera",
  "São Luís",
  "Imperatriz",
  "São José de Ribamar",
  "Timon",
  "Caxias",
  "Paço do Lumiar",
  "Codó",
  "Açailândia",
  "Bacabal",
  "Balsas",
  "Santa Inês",
  "Barra do Corda",
  "Pinheiro",
  "Chapadinha",
  "Buriticupu",
  "Santa Luzia",
  "Grajaú",
  "Itapecuru-Mirim",
  "Coroatá",
  "Barreirinhas",
  "Tutóia",
  "Vargem Grande",
  "Viana",
  "Zé Doca",
  "Lago da Pedra",
  "Coelho Neto",
  "Presidente Dutra",
  "Araioses",
  "São Bento",
  "Rosário",
  "Estreito",
  "Santa Helena",
  "Tuntum",
  "Amarante do Maranhão",
  "Bom Jardim",
  "São Mateus do Maranhão",
  "Colinas",
  "Pedreiras",
  "Penalva",
  "Santa Rita",
  "Brejo",
  "Turiaçu",
  "Parnarama",
  "Bom Jesus das Selvas",
  "São Domingos do Maranhão",
  "Matões",
  "Monção",
  "Urbano Santos",
  "Pindaré-Mirim",
  "Vitória do Mearim",
  "Arame",
  "Cururupu",
  "Alto Alegre do Pindaré",
  "Raposa",
  "Vitorino Freire",
  "Arari",
  "Timbiras",
  "Humberto de Campos",
  "Miranda do Norte",
  "Buriti",
  "São Bernardo",
  "Alto Alegre do Maranhão",
  "Icatu",
  "Anajatuba",
  "Aldeias Altas",
  "Itinga do Maranhão",
  "Turilândia",
  "São João dos Patos",
  "Santa Quitéria do Maranhão",
  "Pedro do Rosário",
  "Governador Nunes Freire",
  "Santa Luzia do Paruá",
  "Porto Franco",
  "Carolina",
  "Carutapera",
  "Buriti Bravo",
  "João Lisboa",
  "Matinha",
  "Peritoró",
  "Dom Pedro",
  "São Vicente Ferrer",
  "Cantanhede",
  "Trizidela do Vale",
  "Alcântara",
  "Centro Novo do Maranhão",
  "Maracaçumé",
  "Paraibano",
  "Bequimão",
  "Pio XII",
  "Nova Olinda do Maranhão",
  "Paulo Ramos",
  "Mirador",
  "São João Batista",
  "Cândido Mendes",
  "Riachão",
  "Magalhães de Almeida",
  "Palmeirândia",
  "Morros",
  "Pastos Bons",
  "Olho d'Água das Cunhãs",
  "Cajari",
  "Formosa da Serra Negra",
  "Passagem Franca",
  "Presidente Sarney",
  "São Raimundo das Mangabeiras",
  "Barão de Grajaú",
  "Pirapemas",
  "São Benedito do Rio Preto",
  "São João do Soter",
  "Governador Edison Lobão",
  "Bacuri",
  "São Luís Gonzaga do Maranhão",
  "Sítio Novo",
  "Gonçalves Dias",
  "Fortuna",
  "Apicum-Açu",
  "Bacabeira",
  "Poção de Pedras",
  "Matões do Norte",
  "Jenipapo dos Vieiras",
  "Mata Roma",
  "Esperantinópolis",
  "Maranhãozinho",
  "Bom Lugar",
  "Conceição do Lago Açu",
  "Lago Verde",
  "Paulino Neves",
  "Joselândia",
  "Santo Amaro do Maranhão",
  "Itaipava do Grajaú",
  "Anapurus",
  "São João do Caru",
  "Araguanã",
  "Primeira Cruz",
  "Buritirana",
  "Mirinzal",
  "Olinda Nova do Maranhão",
  "Cidelândia",
  "Nina Rodrigues",
  "Governador Eugênio Barros",
  "Campestre do Maranhão",
  "Santo Antônio dos Lopes",
  "Igarapé do Meio",
  "Peri Mirim",
  "Satubinha",
  "Senador La Rocque",
  "Centro do Guilherme",
  "Vila Nova dos Martírios",
  "Santana do Maranhão",
  "Presidente Juscelino",
  "Davinópolis",
  "São Pedro da Água Branca",
  "Água Doce do Maranhão",
  "Fortaleza dos Nogueiras",
  "Loreto",
  "Axixá",
  "São Francisco do Maranhão",
  "Godofredo Viana",
  "São Francisco do Brejão",
  "Guimarães",
  "Lima Campos",
  "Lagoa Grande do Maranhão",
  "Igarapé Grande",
  "Duque Bacelar",
  "Bela Vista do Maranhão",
  "Presidente Vargas",
  "Senador Alexandre Costa",
  "Lagoa do Mato",
  "Cajapió",
  "Alto Parnaíba",
  "São João do Paraíso",
  "Capinzal do Norte",
  "Governador Archer",
  "Lago do Junco",
  "Cedral",
  "Sucupira do Norte",
  "Fernando Falcão",
  "Jatobá",
  "Serrano do Maranhão",
  "Governador Newton Bello",
  "Cachoeira Grande",
  "Montes Altos",
  "Brejo de Areia",
  "Lago dos Rodrigues",
  "Central do Maranhão",
  "Tasso Fragoso",
  "Feira Nova do Maranhão",
  "Milagres do Maranhão",
  "Boa Vista do Gurupi",
  "Altamira do Maranhão",
  "Governador Luiz Rocha",
  "Santa Filomena do Maranhão",
  "Ribamar Fiquene",
  "Marajá do Sena",
  "Lajeado Novo",
  "São José dos Basílios",
  "Belágua",
  "São Domingos do Azeitão",
  "Presidente Médici",
  "Amapá do Maranhão",
  "Luís Domingues",
  "São Roberto",
  "Afonso Cunha",
  "Graça Aranha",
  "Bernardo do Mearim",
  "Porto Rico do Maranhão",
  "Tufilândia",
  "Bacurituba",
  "Sucupira do Riachão",
  "Sambaíba",
  "Benedito Leite",
  "Nova Colinas",
  "São Raimundo do Doca Bezerra",
  "São Pedro dos Crentes",
  "Nova Iorque",
  "São Félix de Balsas",
  "Junco do Maranhão",
  "Cuiabá",
  "Várzea Grande",
  "Rondonópolis",
  "Sinop",
  "Sorriso",
  "Tangará da Serra",
  "Cáceres",
  "Lucas do Rio Verde",
  "Primavera do Leste",
  "Barra do Garças",
  "Alta Floresta",
  "Nova Mutum",
  "Pontes e Lacerda",
  "Campo Verde",
  "Juína",
  "Colniza",
  "Campo Novo do Parecis",
  "Guarantã do Norte",
  "Peixoto de Azevedo",
  "Barra do Bugres",
  "Juara",
  "Colíder",
  "Poconé",
  "Confresa",
  "Mirassol d'Oeste",
  "Jaciara",
  "Sapezal",
  "Vila Rica",
  "Água Boa",
  "Paranatinga",
  "Aripuanã",
  "Chapada dos Guimarães",
  "Diamantino",
  "Canarana",
  "Nova Xavantina",
  "São José do Rio Claro",
  "Comodoro",
  "Nova Olímpia",
  "Cotriguaçu",
  "Brasnorte",
  "Alto Araguaia",
  "São José dos Quatro Marcos",
  "Querência",
  "Pedra Preta",
  "Santo Antônio de Leverger",
  "Araputanga",
  "Matupá",
  "Rosário Oeste",
  "Juruena",
  "Vila Bela da Santíssima Trindade",
  "Campinápolis",
  "Nova Bandeirantes",
  "Poxoréu",
  "Guiratinga",
  "Nobres",
  "Feliz Natal",
  "Tapurah",
  "Itiquira",
  "Nossa Senhora do Livramento",
  "Nova Canaã do Norte",
  "Porto Alegre do Norte",
  "Nova Ubiratã",
  "Cláudia",
  "Alto Garças",
  "Porto Esperidião",
  "São Félix do Araguaia",
  "Vera",
  "Alto Paraguai",
  "Alto Taquari",
  "Paranaíta",
  "Juscimeira",
  "Ribeirão Cascalheira",
  "Apiacás",
  "Marcelândia",
  "Carlinda",
  "Denise",
  "Novo Mundo",
  "Arenápolis",
  "Nova Monte Verde",
  "Tabaporã",
  "Terra Nova do Norte",
  "Nova Maringá",
  "Castanheira",
  "Santa Terezinha",
  "Jangada",
  "Jauru",
  "Ipiranga do Norte",
  "Barão de Melgaço",
  "Dom Aquino",
  "Gaúcha do Norte",
  "Campos de Júlio",
  "Alto Boa Vista",
  "Itanhangá",
  "Pontal do Araguaia",
  "Nova Lacerda",
  "Bom Jesus do Araguaia",
  "Lambari d'Oeste",
  "Nortelândia",
  "General Carneiro",
  "Cocalinho",
  "São José do Xingu",
  "Santo Antônio do Leste",
  "Porto dos Gaúchos",
  "Acorizal",
  "Curvelândia",
  "Rio Branco",
  "Novo São Joaquim",
  "São Pedro da Cipa",
  "Canabrava do Norte",
  "Santa Carmem",
  "Nova Guarita",
  "Conquista d'Oeste",
  "São José do Povo",
  "Novo Horizonte do Norte",
  "Rondolândia",
  "Nova Nazaré",
  "Tesouro",
  "Nova Santa Helena",
  "Nova Brasilândia",
  "Itaúba",
  "Santa Rita do Trivelato",
  "Torixoréu",
  "União do Sul",
  "Figueirópolis d'Oeste",
  "Nova Marilândia",
  "Salto do Céu",
  "Santo Afonso",
  "Vale de São Domingos",
  "Araguaiana",
  "Glória d'Oeste",
  "Indiavaí",
  "Porto Estrela",
  "Novo Santo Antônio",
  "Reserva do Cabaçal",
  "Santa Cruz do Xingu",
  "Planalto da Serra",
  "Ribeirãozinho",
  "Luciara",
  "Serra Nova Dourada",
  "Ponte Branca",
  "Araguainha",
  "Campo Grande",
  "Dourados",
  "Três Lagoas",
  "Corumbá",
  "Ponta Porã",
  "Sidrolândia",
  "Naviraí",
  "Nova Andradina",
  "Maracaju",
  "Aquidauana",
  "Paranaíba",
  "Amambai",
  "Rio Brilhante",
  "Coxim",
  "Caarapó",
  "Miranda",
  "São Gabriel do Oeste",
  "Chapadão do Sul",
  "Aparecida do Taboado",
  "Jardim",
  "Itaporã",
  "Anastácio",
  "Ribas do Rio Pardo",
  "Bela Vista",
  "Ladário",
  "Bataguassu",
  "Ivinhema",
  "Nova Alvorada do Sul",
  "Terenos",
  "Bonito",
  "Cassilândia",
  "Itaquiraí",
  "Costa Rica",
  "Sonora",
  "Rio Verde de Mato Grosso",
  "Fátima do Sul",
  "Mundo Novo",
  "Porto Murtinho",
  "Iguatemi",
  "Água Clara",
  "Coronel Sapucaia",
  "Paranhos",
  "Nioaque",
  "Camapuã",
  "Deodápolis",
  "Aral Moreira",
  "Eldorado",
  "Brasilândia",
  "Tacuru",
  "Dois Irmãos do Buriti",
  "Batayporã",
  "Angélica",
  "Sete Quedas",
  "Glória de Dourados",
  "Guia Lopes da Laguna",
  "Japorã",
  "Anaurilândia",
  "Antônio João",
  "Santa Rita do Pardo",
  "Bodoquena",
  "Pedro Gomes",
  "Inocência",
  "Laguna Carapã",
  "Jaraguari",
  "Bandeirantes",
  "Juti",
  "Selvíria",
  "Caracol",
  "Corguinho",
  "Vicentina",
  "Douradina",
  "Paraíso das Águas",
  "Alcinópolis",
  "Rochedo",
  "Rio Negro",
  "Jateí",
  "Taquarussu",
  "Novo Horizonte do Sul",
  "Figueirão",
  "Belo Horizonte",
  "Uberlândia",
  "Contagem",
  "Juiz de Fora",
  "Montes Claros",
  "Betim",
  "Uberaba",
  "Ribeirão das Neves",
  "Governador Valadares",
  "Divinópolis",
  "Ipatinga",
  "Sete Lagoas",
  "Santa Luzia",
  "Ibirité",
  "Poços de Caldas",
  "Patos de Minas",
  "Pouso Alegre",
  "Teófilo Otoni",
  "Varginha",
  "Conselheiro Lafaiete",
  "Sabará",
  "Vespasiano",
  "Barbacena",
  "Araguari",
  "Itabira",
  "Passos",
  "Nova Lima",
  "Araxá",
  "Nova Serrana",
  "Lavras",
  "Coronel Fabriciano",
  "Muriaé",
  "Ubá",
  "Ituiutaba",
  "Itaúna",
  "Pará de Minas",
  "Paracatu",
  "Itajubá",
  "Caratinga",
  "Patrocínio",
  "Manhuaçu",
  "Timóteo",
  "São João del-Rei",
  "Unaí",
  "Curvelo",
  "Alfenas",
  "João Monlevade",
  "Três Corações",
  "Viçosa",
  "Cataguases",
  "Ouro Preto",
  "Esmeraldas",
  "Janaúba",
  "São Sebastião do Paraíso",
  "Januária",
  "Formiga",
  "Lagoa Santa",
  "Pedro Leopoldo",
  "Mariana",
  "Frutal",
  "Ponte Nova",
  "Três Pontas",
  "Pirapora",
  "São Francisco",
  "Congonhas",
  "Campo Belo",
  "Lagoa da Prata",
  "Itabirito",
  "Leopoldina",
  "Guaxupé",
  "Bom Despacho",
  "Bocaiuva",
  "Monte Carmelo",
  "João Pinheiro",
  "Diamantina",
  "São Lourenço",
  "Santos Dumont",
  "Caeté",
  "Igarapé",
  "Santa Rita do Sapucaí",
  "Visconde do Rio Branco",
  "Machado",
  "Almenara",
  "Oliveira",
  "Salinas",
  "Andradas",
  "Brumadinho",
  "Arcos",
  "Nanuque",
  "Boa Esperança",
  "Ouro Branco",
  "Iturama",
  "Várzea da Palma",
  "Jaíba",
  "Matozinhos",
  "Capelinha",
  "Porteirinha",
  "Extrema",
  "Araçuaí",
  "São Gotardo",
  "Santana do Paraíso",
  "Além Paraíba",
  "Piumhi",
  "Itamarandiba",
  "Guanhães",
  "Taiobeiras",
  "Sarzedo",
  "Ouro Fino",
  "Barão de Cocais",
  "Três Marias",
  "Carangola",
  "São Joaquim de Bicas",
  "Brasília de Minas",
  "Pompéu",
  "Santa Bárbara",
  "Mateus Leme",
  "Espinosa",
  "Minas Novas",
  "Novo Cruzeiro",
  "Rio Pardo de Minas",
  "Carmo do Paranaíba",
  "Cambuí",
  "Cláudio",
  "Campos Gerais",
  "Conceição das Alagoas",
  "Santo Antônio do Monte",
  "Elói Mendes",
  "Pitangui",
  "Buritizeiro",
  "Prata",
  "Coromandel",
  "Juatuba",
  "Mantena",
  "Belo Oriente",
  "Mutum",
  "Nepomuceno",
  "Coração de Jesus",
  "Sacramento",
  "Jacutinga",
  "São João Nepomuceno",
  "Francisco Sá",
  "Carandaí",
  "São Gonçalo do Sapucaí",
  "Jequitinhonha",
  "Ibiá",
  "Tupaciguara",
  "Espera Feliz",
  "Buritis",
  "Aimorés",
  "São João da Ponte",
  "Paraopeba",
  "São José da Lapa",
  "Pedra Azul",
  "Monte Sião",
  "Inhapim",
  "Bambuí",
  "Caraí",
  "São João do Paraíso",
  "Raul Soares",
  "Corinto",
  "Abaeté",
  "Itambacuri",
  "Conselheiro Pena",
  "Carmo do Cajuru",
  "Manhumirim",
  "Camanducaia",
  "Itapecerica",
  "Paraguaçu",
  "Perdões",
  "Caxambu",
  "Monte Santo de Minas",
  "Paraisópolis",
  "Monte Alegre de Minas",
  "Carmo do Rio Claro",
  "Campestre",
  "Itaobim",
  "Lambari",
  "Barroso",
  "Serro",
  "Medina",
  "Vazante",
  "Jaboticatubas",
  "Monte Azul",
  "Muzambinho",
  "Padre Paraíso",
  "Turmalina",
  "Ipanema",
  "Alpinópolis",
  "Divino",
  "Santa Vitória",
  "Lajinha",
  "Simonésia",
  "Borda da Mata",
  "Campina Verde",
  "Carmópolis de Minas",
  "Presidente Olegário",
  "Varzelândia",
  "Águas Formosas",
  "Baependi",
  "Matipó",
  "Ervália",
  "Guaranésia",
  "Ipaba",
  "Fronteira",
  "Santo Antônio do Amparo",
  "Malacacheta",
  "Carlos Chagas",
  "Luz",
  "Ladainha",
  "Itacarambi",
  "Lagoa Formosa",
  "Manga",
  "Rio Pomba",
  "Arinos",
  "Cássia",
  "Piranga",
  "Bom Sucesso",
  "Peçanha",
  "Nova Era",
  "Urucuia",
  "Conceição do Mato Dentro",
  "Resplendor",
  "São Domingos do Prata",
  "Brasilândia de Minas",
  "Nova Resende",
  "Poço Fundo",
  "Campanha",
  "Tocantins",
  "Lima Duarte",
  "Poté",
  "Raposos",
  "Perdizes",
  "Passa Quatro",
  "Santa Margarida",
  "Capinópolis",
  "Itaú de Minas",
  "Nova Ponte",
  "Grão Mogol",
  "Papagaios",
  "Itamonte",
  "Mário Campos",
  "São João Evangelista",
  "Campos Altos",
  "Cruzília",
  "Felixlândia",
  "Itanhandu",
  "Itapagipe",
  "Joaíma",
  "Entre Rios de Minas",
  "Capitão Enéas",
  "Sabinópolis",
  "Chapada do Norte",
  "Areado",
  "Miraí",
  "Alvinópolis",
  "Itinga",
  "Carmo de Minas",
  "Botelhos",
  "Candeias",
  "Bom Jesus do Galho",
  "Matias Barbosa",
  "Montalvânia",
  "Bicas",
  "Santa Maria do Suaçuí",
  "Caldas",
  "Alterosa",
  "Santa Juliana",
  "Brazópolis",
  "Astolfo Dutra",
  "Rio Piracicaba",
  "Tarumirim",
  "Guapé",
  "Chapada Gaúcha",
  "Ibiraci",
  "Cabo Verde",
  "Maria da Fé",
  "Conceição do Rio Verde",
  "Virgem da Lapa",
  "Águas Vermelhas",
  "Mirabela",
  "Itaguara",
  "Martinho Campos",
  "Abre Campo",
  "Rio Casca",
  "Dores do Indaiá",
  "Água Boa",
  "São João das Missões",
  "Monte Belo",
  "Lagoa Dourada",
  "Cristais",
  "Mar de Espanha",
  "Itaipé",
  "Cambuquira",
  "São Gonçalo do Pará",
  "São Geraldo",
  "São Romão",
  "Ubaí",
  "Rio Vermelho",
  "Ubaporanga",
  "Ilicínea",
  "Ataléia",
  "Setubinha",
  "Planura",
  "Mato Verde",
  "Rio Paranaíba",
  "Jacinto",
  "Pedras de Maria da Cruz",
  "Itanhomi",
  "Canápolis",
  "Jequeri",
  "Ponto dos Volantes",
  "Congonhal",
  "Icaraí de Minas",
  "Carmo da Cachoeira",
  "Andrelândia",
  "Perdigão",
  "Caetanópolis",
  "Conceição dos Ouros",
  "Berilo",
  "Gouveia",
  "São João do Manhuaçu",
  "Serra do Salitre",
  "Teixeiras",
  "Campo do Meio",
  "Itabirinha",
  "Cachoeira de Minas",
  "Resende Costa",
  "Santo Antônio do Jacinto",
  "Carmo da Mata",
  "Bonito de Minas",
  "Antônio Carlos",
  "Estiva",
  "Porto Firme",
  "Divisópolis",
  "Eugenópolis",
  "Matias Cardoso",
  "Itatiaiuçu",
  "Engenheiro Caldas",
  "Igaratinga",
  "São Gonçalo do Rio Abaixo",
  "Fervedouro",
  "Pedralva",
  "Iapu",
  "Delta",
  "Arceburgo",
  "Bueno Brandão",
  "São Tiago",
  "Prudente de Morais",
  "Jordânia",
  "Santa Maria de Itabira",
  "Miradouro",
  "Novo Oriente de Minas",
  "Juruaia",
  "Pirapetinga",
  "Mercês",
  "Piraúba",
  "Alto Rio Doce",
  "Bom Repouso",
  "Rio Acima",
  "Recreio",
  "Senhora dos Remédios",
  "Virginópolis",
  "Ninheira",
  "Conceição da Aparecida",
  "Centralina",
  "Buenópolis",
  "Urucânia",
  "Francisco Badaró",
  "Guaraciaba",
  "Dores de Campos",
  "Bela Vista de Minas",
  "Rubim",
  "Cristina",
  "Ipuiuna",
  "Itamogi",
  "Carneirinho",
  "Itapeva",
  "Coroaci",
  "Capim Branco",
  "São Sebastião do Maranhão",
  "Formoso",
  "Lontra",
  "Frei Inocêncio",
  "Lagoa Grande",
  "Paula Cândido",
  "Ferros",
  "Verdelândia",
  "Araújos",
  "Riacho dos Machados",
  "Cachoeira de Pajeú",
  "Carbonita",
  "Caputira",
  "Açucena",
  "Antônio Dias",
  "Coronel Murta",
  "Prados",
  "Coqueiral",
  "Rio Novo",
  "Morada Nova de Minas",
  "Guarani",
  "Cordisburgo",
  "Santa Rita de Caldas",
  "Piedade de Caratinga",
  "Coluna",
  "Monsenhor Paulo",
  "Serra dos Aimorés",
  "Santa Cruz de Minas",
  "Pimenta",
  "Nazareno",
  "Mata Verde",
  "Capitólio",
  "Piranguinho",
  "Santana do Manhuaçu",
  "Virgínia",
  "Martins Soares",
  "Angelândia",
  "Pratápolis",
  "São Gonçalo do Abaeté",
  "Ibiaí",
  "Araponga",
  "Pavão",
  "Campo Florido",
  "Montezuma",
  "Rodeiro",
  "Pains",
  "Guiricema",
  "Pocrane",
  "Alto Jequitibá",
  "Santa Bárbara do Leste",
  "Guimarânia",
  "Tiradentes",
  "Orizânia",
  "Riachinho",
  "Maravilhas",
  "Estrela do Sul",
  "Passa Tempo",
  "Delfim Moreira",
  "Japonvar",
  "Senador Firmino",
  "Iguatama",
  "Durandé",
  "São Vicente de Minas",
  "Curral de Dentro",
  "Jenipapo de Minas",
  "Baldim",
  "Cônego Marinho",
  "Belo Vale",
  "Jacuí",
  "Tombos",
  "Serrania",
  "Divinolândia de Minas",
  "Limeira do Oeste",
  "São Pedro dos Ferros",
  "Coimbra",
  "Inimutaba",
  "Florestal",
  "Moema",
  "Lagamar",
  "Felisburgo",
  "São João Batista do Glória",
  "Pintópolis",
  "Santana de Pirapama",
  "São José da Barra",
  "Dionísio",
  "Nova Porteirinha",
  "Claro dos Poções",
  "Alpercata",
  "Jequitaí",
  "São João do Oriente",
  "Inconfidentes",
  "Sericita",
  "Indaiabira",
  "Santa Rita de Minas",
  "Santo Antônio do Retiro",
  "Desterro de Entre Rios",
  "Reduto",
  "Engenheiro Navarro",
  "Varjão de Minas",
  "Pedra Bonita",
  "São Tomé das Letras",
  "Delfinópolis",
  "Machacalis",
  "Naque",
  "São Roque de Minas",
  "Iraí de Minas",
  "Central de Minas",
  "Alfredo Vasconcelos",
  "Santana da Vargem",
  "Sapucaí-Mirim",
  "Guidoval",
  "Cabeceira Grande",
  "Abadia dos Dourados",
  "Salto da Divisa",
  "Indianópolis",
  "Conquista",
  "Araporã",
  "São Tomás de Aquino",
  "Imbé de Minas",
  "São Miguel do Anta",
  "São Sebastião do Oeste",
  "Divisa Alegre",
  "Confins",
  "Capetinga",
  "Laranjal",
  "Bonfim",
  "Careaçu",
  "Crisólita",
  "Cipotânea",
  "Tumiritinga",
  "Galileia",
  "Periquito",
  "Luislândia",
  "São Sebastião do Anta",
  "Ijaci",
  "Dona Euzébia",
  "Comercinho",
  "Heliodora",
  "Palma",
  "Mamonas",
  "Guarda-Mor",
  "São Francisco de Paula",
  "Lassance",
  "Pirajuba",
  "Padre Carvalho",
  "Vargem Alegre",
  "Mendes Pimentel",
  "Bom Jardim de Minas",
  "Córrego Fundo",
  "Sardoá",
  "São José do Jacuri",
  "Santa Helena de Minas",
  "Piracema",
  "Tiros",
  "Inhaúma",
  "Toledo",
  "São Francisco de Sales",
  "Botumirim",
  "Silvianópolis",
  "Luisburgo",
  "Olhos-d'Água",
  "Soledade de Minas",
  "Catuji",
  "Gonzaga",
  "Bom Jesus do Amparo",
  "Pai Pedro",
  "Itueta",
  "Divisa Nova",
  "Patis",
  "Cristália",
  "Itumirim",
  "São João do Manteninha",
  "Munhoz",
  "Aiuruoca",
  "Alto Caparaó",
  "Rio Manso",
  "Ouro Verde de Minas",
  "Pouso Alto",
  "Frei Gaspar",
  "Bandeira do Sul",
  "Senhora de Oliveira",
  "Patrocínio do Muriaé",
  "Nova União",
  "Veredinha",
  "Juvenília",
  "Chalé",
  "São Domingos das Dores",
  "Rubelita",
  "São Sebastião da Bela Vista",
  "Cana Verde",
  "Caiana",
  "Capitão Andrade",
  "Conceição do Pará",
  "Gurinhatã",
  "Piranguçu",
  "Rio Preto",
  "Mesquita",
  "Sobrália",
  "Catas Altas",
  "Caparaó",
  "Jampruca",
  "Itacambira",
  "Datas",
  "Luminárias",
  "Santa Rita do Itueto",
  "São Bento Abade",
  "Bonfinópolis de Minas",
  "Entre Folhas",
  "Senador Amaral",
  "São José do Goiabal",
  "Novorizonte",
  "Ibiracatu",
  "Rio Espera",
  "Itaverava",
  "Presidente Bernardes",
  "Barão de Monte Alto",
  "Aricanduva",
  "Virgolândia",
  "Franciscópolis",
  "Volta Grande",
  "Francisco Dumont",
  "Fruta de Leite",
  "Dom Silvério",
  "Jequitibá",
  "Santa Maria do Salto",
  "Palmópolis",
  "Cristiano Otoni",
  "São Pedro do Suaçuí",
  "São José da Varginha",
  "Dores de Guanhães",
  "Madre de Deus de Minas",
  "Rio do Prado",
  "José Raydan",
  "Turvolândia",
  "Bocaina de Minas",
  "Gameleiras",
  "Crucilândia",
  "Congonhas do Norte",
  "Vargem Grande do Rio Pardo",
  "Descoberto",
  "Piedade dos Gerais",
  "Pingo-d'Água",
  "Cuparaque",
  "Dom Cavati",
  "Guaraciama",
  "Ibertioga",
  "Liberdade",
  "Divino das Laranjeiras",
  "São João da Lagoa",
  "Moeda",
  "Catuti",
  "Miravânia",
  "Monte Formoso",
  "Leme do Prado",
  "Josenópolis",
  "Barra Longa",
  "Tapira",
  "Claraval",
  "Vermelho Novo",
  "Santana do Jacaré",
  "Santa Rita de Jacutinga",
  "Serranópolis de Minas",
  "Augusto de Lima",
  "Ressaquinha",
  "Jeceaba",
  "Paulistas",
  "Berizal",
  "Jesuânia",
  "São Francisco do Glória",
  "Joaquim Felício",
  "Bandeira",
  "Braúnas",
  "Espírito Santo do Dourado",
  "Natércia",
  "Santa Cruz do Escalvado",
  "Oratórios",
  "Felício dos Santos",
  "Rosário da Limeira",
  "Amparo da Serra",
  "Capela Nova",
  "Bertópolis",
  "Conceição de Ipanema",
  "Cantagalo",
  "São Pedro da União",
  "Aguanil",
  "Fronteira dos Vales",
  "Canaã",
  "Ritápolis",
  "São João do Pacuí",
  "José Gonçalves de Minas",
  "Fortaleza de Minas",
  "Pequi",
  "Carvalhos",
  "Paineiras",
  "Couto de Magalhães de Minas",
  "Dom Joaquim",
  "Piedade do Rio Grande",
  "Funilândia",
  "Japaraíba",
  "Materlândia",
  "Itamarati de Minas",
  "Santa Bárbara do Tugúrio",
  "Joanésia",
  "Gonçalves",
  "Juramento",
  "Santa Efigênia de Minas",
  "Santana do Riacho",
  "Ponto Chique",
  "Serra Azul de Minas",
  "São José da Safira",
  "Bom Jesus da Penha",
  "União de Minas",
  "Pescador",
  "Brás Pires",
  "Ipiaçu",
  "São José do Alegre",
  "Dores do Turvo",
  "Piedade de Ponte Nova",
  "Taquaraçu de Minas",
  "Tocos do Moji",
  "São Geraldo do Baixio",
  "Veríssimo",
  "Marilac",
  "Santa Cruz de Salinas",
  "Lagoa dos Patos",
  "Ribeirão Vermelho",
  "Senador Modestino Gonçalves",
  "Carrancas",
  "Marliéria",
  "Goianá",
  "Acaiaca",
  "Santana do Deserto",
  "Bugre",
  "Pedra do Indaiá",
  "Cajuri",
  "Conceição da Barra de Minas",
  "Ewbank da Câmara",
  "Santana de Cataguases",
  "Minduri",
  "Medeiros",
  "Santo Antônio do Grama",
  "São Geraldo da Piedade",
  "São José do Divino",
  "Campo Azul",
  "Santa Fé de Minas",
  "Alvarenga",
  "Diogo de Vasconcelos",
  "São Brás do Suaçuí",
  "Santo Antônio do Itambé",
  "Guarará",
  "Santana dos Montes",
  "Itutinga",
  "Campanário",
  "Matutina",
  "Córrego do Bom Jesus",
  "Tabuleiro",
  "Catas Altas da Noruega",
  "Pratinha",
  "Cruzeiro da Fortaleza",
  "Pedrinópolis",
  "Dom Bosco",
  "Carvalhópolis",
  "Alvorada de Minas",
  "Quartel Geral",
  "Santo Antônio do Aventureiro",
  "Cachoeira da Prata",
  "Presidente Juscelino",
  "Vieiras",
  "Nova Módica",
  "Cordislândia",
  "Senhora do Porto",
  "Romaria",
  "Fernandes Tourinho",
  "Ibitiúra de Minas",
  "Frei Lagonegro",
  "Estrela do Indaiá",
  "Coronel Xavier Chaves",
  "Divinésia",
  "Belmiro Braga",
  "Goiabeira",
  "Santa Rita de Ibitipoca",
  "Lamim",
  "Santa Rosa da Serra",
  "São Félix de Minas",
  "Pequeri",
  "Natalândia",
  "Bias Fortes",
  "Uruana de Minas",
  "Leandro Ferreira",
  "Nacip Raydan",
  "Chácara",
  "Santa Bárbara do Monte Verde",
  "Faria Lemos",
  "São Gonçalo do Rio Preto",
  "Glaucilândia",
  "Córrego Danta",
  "Mathias Lobato",
  "Onça de Pitangui",
  "Jaguaraçu",
  "Caranaíba",
  "Comendador Gomes",
  "Morro do Pilar",
  "Cascalho Rico",
  "Coronel Pacheco",
  "Taparuba",
  "Nova Belém",
  "Santo Hipólito",
  "São Sebastião da Vargem Alegre",
  "Albertina",
  "Ibituruna",
  "Maripá de Minas",
  "Presidente Kubitschek",
  "Dom Viçoso",
  "Fortuna de Minas",
  "Pedra do Anta",
  "Desterro do Melo",
  "Camacho",
  "Arapuá",
  "Olímpio Noronha",
  "São José do Mantimento",
  "Conceição das Pedras",
  "Ingaí",
  "Arantina",
  "São João da Mata",
  "Cachoeira Dourada",
  "Piau",
  "Marmelópolis",
  "Córrego Novo",
  "Argirita",
  "Carmésia",
  "Alagoa",
  "Chiador",
  "Rio Doce",
  "Simão Pereira",
  "Umburatiba",
  "Sem-Peixe",
  "Pedra Dourada",
  "Wenceslau Braz",
  "Santana do Garambéu",
  "Biquinhas",
  "Morro da Garça",
  "Fama",
  "Araçaí",
  "Rochedo de Minas",
  "Estrela Dalva",
  "Silveirânia",
  "São Sebastião do Rio Verde",
  "Casa Grande",
  "Monjolos",
  "Vargem Bonita",
  "Oliveira Fortes",
  "Aracitaba",
  "Itambé do Mato Dentro",
  "Passa Vinte",
  "Senador Cortes",
  "Água Comprida",
  "Serranos",
  "Queluzito",
  "Douradoquara",
  "Tapiraí",
  "Seritinga",
  "Pedro Teixeira",
  "Consolação",
  "Santo Antônio do Rio Abaixo",
  "Olaria",
  "Passabém",
  "Antônio Prado de Minas",
  "Doresópolis",
  "Paiva",
  "São Sebastião do Rio Preto",
  "Senador José Bento",
  "Grupiara",
  "Cedro do Abaeté",
  "Serra da Saudade",
  "Belém",
  "Ananindeua",
  "Santarém",
  "Marabá",
  "Parauapebas",
  "Castanhal",
  "Abaetetuba",
  "Cametá",
  "Barcarena",
  "Altamira",
  "Itaituba",
  "Bragança",
  "Marituba",
  "Breves",
  "Paragominas",
  "Tucuruí",
  "Tailândia",
  "São Félix do Xingu",
  "Redenção",
  "Moju",
  "Novo Repartimento",
  "Santana do Araguaia",
  "Oriximiná",
  "Santa Izabel do Pará",
  "Capanema",
  "Breu Branco",
  "Ipixuna do Pará",
  "Benevides",
  "Tomé-Açu",
  "Portel",
  "Igarapé-Miri",
  "Ulianópolis",
  "Viseu",
  "Dom Eliseu",
  "Jacundá",
  "São Miguel do Guamá",
  "Juruti",
  "Monte Alegre",
  "Alenquer",
  "Acará",
  "Vigia",
  "Capitão Poço",
  "Itupiranga",
  "Rondon do Pará",
  "Óbidos",
  "Rurópolis",
  "Baião",
  "Pacajá",
  "Conceição do Araguaia",
  "Augusto Corrêa",
  "Xinguara",
  "Uruará",
  "Porto de Moz",
  "Goianésia do Pará",
  "Muaná",
  "Salinópolis",
  "Curuçá",
  "Tucumã",
  "Afuá",
  "Igarapé-Açu",
  "Canaã dos Carajás",
  "Curralinho",
  "Cachoeira do Piriá",
  "Concórdia do Pará",
  "Gurupá",
  "Eldorado dos Carajás",
  "Almeirim",
  "Ourilândia do Norte",
  "Oeiras do Pará",
  "Irituia",
  "Medicilândia",
  "Santo Antônio do Tauá",
  "Placas",
  "São Domingos do Capim",
  "Aurora do Pará",
  "Ponta de Pedras",
  "Bagre",
  "Mocajuba",
  "Tracuateua",
  "Mãe do Rio",
  "Anajás",
  "Prainha",
  "Bujaru",
  "Limoeiro do Ajuru",
  "Maracanã",
  "Anapu",
  "Marapanim",
  "Melgaço",
  "Água Azul do Norte",
  "São Sebastião da Boa Vista",
  "Garrafão do Norte",
  "São Domingos do Araguaia",
  "Novo Progresso",
  "Soure",
  "Santa Maria do Pará",
  "São Geraldo do Araguaia",
  "Salvaterra",
  "Cachoeira do Arari",
  "Chaves",
  "São João de Pirabas",
  "Santa Maria das Barreiras",
  "Santa Bárbara do Pará",
  "Nova Esperança do Piriá",
  "Floresta do Araguaia",
  "Santa Luzia do Pará",
  "Trairão",
  "Terra Santa",
  "Rio Maria",
  "São Caetano de Odivelas",
  "Ourém",
  "Belterra",
  "Curionópolis",
  "Bom Jesus do Tocantins",
  "Nova Ipixuna",
  "Bonito",
  "Aveiro",
  "Mojuí dos Campos",
  "São Francisco do Pará",
  "Nova Timboteua",
  "Vitória do Xingu",
  "Brasil Novo",
  "Curuá",
  "São João do Araguaia",
  "Cumaru do Norte",
  "Quatipuru",
  "Piçarra",
  "Colares",
  "Inhangapi",
  "Terra Alta",
  "Senador José Porfírio",
  "Primavera",
  "Santa Cruz do Arari",
  "Magalhães Barata",
  "Peixe-Boi",
  "Palestina do Pará",
  "Abel Figueiredo",
  "Brejo Grande do Araguaia",
  "Jacareacanga",
  "Faro",
  "Santarém Novo",
  "São João da Ponta",
  "Sapucaia",
  "Pau-d'Arco",
  "Bannach",
  "João Pessoa",
  "Campina Grande",
  "Santa Rita",
  "Patos",
  "Bayeux",
  "Sousa",
  "Cabedelo",
  "Cajazeiras",
  "Guarabira",
  "Sapé",
  "Mamanguape",
  "Queimadas",
  "São Bento",
  "Monteiro",
  "Esperança",
  "Pombal",
  "Catolé do Rocha",
  "Pedras de Fogo",
  "Alagoa Grande",
  "Lagoa Seca",
  "Solânea",
  "Conde",
  "Itaporanga",
  "Itabaiana",
  "Rio Tinto",
  "Princesa Isabel",
  "Areia",
  "Caaporã",
  "Mari",
  "Bananeiras",
  "Alagoa Nova",
  "Araruna",
  "São José de Piranhas",
  "Cuité",
  "Remígio",
  "Alhandra",
  "Pitimbu",
  "Aroeiras",
  "Conceição",
  "Itapororoca",
  "Pocinhos",
  "Picuí",
  "Juazeirinho",
  "Ingá",
  "São João do Rio do Peixe",
  "Boqueirão",
  "Belém",
  "Cruz do Espírito Santo",
  "Cacimba de Dentro",
  "Sumé",
  "Araçagi",
  "Piancó",
  "Barra de Santa Rosa",
  "Taperoá",
  "Santa Luzia",
  "Coremas",
  "Uiraúna",
  "Teixeira",
  "Soledade",
  "Tavares",
  "Alagoinha",
  "Jacaraú",
  "Brejo do Cruz",
  "Gurinhém",
  "Massaranduba",
  "Serra Branca",
  "Puxinanã",
  "Arara",
  "Lucena",
  "Mogeiro",
  "Paulista",
  "Bonito de Santa Fé",
  "Salgado de São Félix",
  "Pilar",
  "Imaculada",
  "São Sebastião de Lagoa de Roça",
  "Fagundes",
  "Itatuba",
  "Tacima",
  "Manaíra",
  "São Vicente do Seridó",
  "Juripiranga",
  "Nova Floresta",
  "Pirpirituba",
  "Natuba",
  "Água Branca",
  "Dona Inês",
  "Cachoeira dos Índios",
  "Mulungu",
  "Umbuzeiro",
  "Juru",
  "Triunfo",
  "Baía da Traição",
  "Marcação",
  "Mataraca",
  "Riacho dos Cavalos",
  "Aparecida",
  "Barra de Santana",
  "Desterro",
  "Gado Bravo",
  "Juarez Távora",
  "Pedra Lavrada",
  "Cubati",
  "Sobrado",
  "Lagoa de Dentro",
  "Jericó",
  "São Mamede",
  "São José da Lagoa Tapada",
  "Casserengue",
  "São Miguel de Taipu",
  "Belém do Brejo do Cruz",
  "Livramento",
  "Nazarezinho",
  "Junco do Seridó",
  "Cacimbas",
  "Boa Vista",
  "Caiçara",
  "Areial",
  "Serra Redonda",
  "Santana dos Garrotes",
  "Cuitegi",
  "Capim",
  "Matureia",
  "Marizópolis",
  "Condado",
  "Santa Cruz",
  "Santa Cecília",
  "Pilões",
  "Diamante",
  "Brejo dos Santos",
  "Olho d'Água",
  "São José de Caiana",
  "Cuité de Mamanguape",
  "Pedro Régis",
  "Barra de São Miguel",
  "Igaracy",
  "Caldas Brandão",
  "Camalaú",
  "São José dos Ramos",
  "Serraria",
  "Nova Olinda",
  "Ibiara",
  "Santa Helena",
  "Montadas",
  "Malta",
  "Cabaceiras",
  "Aguiar",
  "Alcantil",
  "Damião",
  "Vieirópolis",
  "Borborema",
  "Boa Ventura",
  "Curral de Cima",
  "Sertãozinho",
  "Santana de Mangueira",
  "Baraúna",
  "Nova Palmeira",
  "Catingueira",
  "Bom Sucesso",
  "Pilõezinhos",
  "Caturité",
  "Monte Horebe",
  "Congo",
  "Lagoa",
  "São José de Espinharas",
  "São Bentinho",
  "Riachão do Poço",
  "Riachão do Bacamarte",
  "Santa Teresinha",
  "Matinhas",
  "São João do Tigre",
  "Logradouro",
  "Poço de José de Moura",
  "Prata",
  "Caraúbas",
  "São João do Cariri",
  "São José do Sabugi",
  "Assunção",
  "Olivedos",
  "Mãe d'Água",
  "Salgadinho",
  "São José de Princesa",
  "Poço Dantas",
  "Vista Serrana",
  "Pedra Branca",
  "Cacimba de Areia",
  "Riachão",
  "Sossêgo",
  "São José do Bonfim",
  "São José dos Cordeiros",
  "Santa Inês",
  "Bernardino Batista",
  "Duas Estradas",
  "Emas",
  "São Sebastião do Umbuzeiro",
  "Gurjão",
  "São Francisco",
  "Cajazeirinhas",
  "São Domingos",
  "Serra da Raiz",
  "Tenório",
  "Ouro Velho",
  "Frei Martinho",
  "Mato Grosso",
  "Serra Grande",
  "Várzea",
  "Carrapateira",
  "Lastro",
  "São Domingos do Cariri",
  "Joca Claudino",
  "Algodão de Jandaíra",
  "Bom Jesus",
  "Curral Velho",
  "Santo André",
  "Passagem",
  "Zabelê",
  "Amparo",
  "Areia de Baraúnas",
  "Quixaba",
  "Riacho de Santo Antônio",
  "Coxixola",
  "São José do Brejo do Cruz",
  "Parari",
  "Curitiba",
  "Londrina",
  "Maringá",
  "Ponta Grossa",
  "Cascavel",
  "São José dos Pinhais",
  "Foz do Iguaçu",
  "Colombo",
  "Guarapuava",
  "Araucária",
  "Toledo",
  "Fazenda Rio Grande",
  "Paranaguá",
  "Campo Largo",
  "Apucarana",
  "Pinhais",
  "Almirante Tamandaré",
  "Arapongas",
  "Piraquara",
  "Sarandi",
  "Umuarama",
  "Cambé",
  "Campo Mourão",
  "Francisco Beltrão",
  "Paranavaí",
  "Cianorte",
  "Pato Branco",
  "Telêmaco Borba",
  "Castro",
  "Rolândia",
  "Irati",
  "União da Vitória",
  "Ibiporã",
  "Marechal Cândido Rondon",
  "Prudentópolis",
  "Palmas",
  "Lapa",
  "Cornélio Procópio",
  "São Mateus do Sul",
  "Medianeira",
  "Santo Antônio da Platina",
  "Campina Grande do Sul",
  "Paiçandu",
  "Dois Vizinhos",
  "Jacarezinho",
  "Guaratuba",
  "Marialva",
  "Matinhos",
  "Jaguariaíva",
  "Quedas do Iguaçu",
  "Rio Negro",
  "Mandaguari",
  "Palmeira",
  "Guaíra",
  "Assis Chateaubriand",
  "Imbituva",
  "Pinhão",
  "Rio Branco do Sul",
  "Palotina",
  "Laranjeiras do Sul",
  "Ivaiporã",
  "Ibaiti",
  "Bandeirantes",
  "Campo Magro",
  "Pitanga",
  "Itaperuçu",
  "Goioerê",
  "Pontal do Paraná",
  "Arapoti",
  "Nova Esperança",
  "Mandirituba",
  "São Miguel do Iguaçu",
  "Santa Helena",
  "Reserva",
  "Astorga",
  "Piraí do Sul",
  "Cambará",
  "Colorado",
  "Quatro Barras",
  "Carambeí",
  "Santa Terezinha de Itaipu",
  "Loanda",
  "Mandaguaçu",
  "Altônia",
  "Ortigueira",
  "Siqueira Campos",
  "Jandaia do Sul",
  "Cruzeiro do Oeste",
  "Ubiratã",
  "Tibagi",
  "Coronel Vivida",
  "Santo Antônio do Sudoeste",
  "Andirá",
  "Ampére",
  "Sengés",
  "Quitandinha",
  "Wenceslau Braz",
  "Capanema",
  "Chopinzinho",
  "Contenda",
  "Antonina",
  "Cafelândia",
  "Cruz Machado",
  "Matelândia",
  "Cerro Azul",
  "Terra Roxa",
  "Faxinal",
  "Terra Boa",
  "Tijucas do Sul",
  "Corbélia",
  "Terra Rica",
  "Realeza",
  "Mangueirinha",
  "Morretes",
  "Tapejara",
  "Sertanópolis",
  "Bituruna",
  "Clevelândia",
  "Candói",
  "Capitão Leônidas Marques",
  "Rio Azul",
  "Bela Vista do Paraíso",
  "São João do Triunfo",
  "Ipiranga",
  "Curiúva",
  "Tamarana",
  "Rebouças",
  "Salto do Lontra",
  "Alto Paraná",
  "Santa Izabel do Oeste",
  "Assaí",
  "Cândido de Abreu",
  "Marmeleiro",
  "Carlópolis",
  "Paraíso do Norte",
  "Ivaí",
  "Araruna",
  "Peabiru",
  "Engenheiro Beltrão",
  "Campina da Lagoa",
  "Jaguapitã",
  "Mallet",
  "General Carneiro",
  "Iporã",
  "Manoel Ribas",
  "Imbaú",
  "Planalto",
  "Cantagalo",
  "Bocaiuva do Sul",
  "Rio Bonito do Iguaçu",
  "Balsa Nova",
  "Nova Londrina",
  "Piên",
  "Turvo",
  "Cidade Gaúcha",
  "Mamborê",
  "Ribeirão do Pinhal",
  "Teixeira Soares",
  "Palmital",
  "Jataizinho",
  "Porecatu",
  "Santa Fé",
  "Ventania",
  "Querência do Norte",
  "Itapejara d'Oeste",
  "Joaquim Távora",
  "Três Barras do Paraná",
  "Guaraniaçu",
  "Moreira Sales",
  "Céu Azul",
  "Paranacity",
  "Alvorada do Sul",
  "Itaipulândia",
  "Santa Mariana",
  "Nova Laranjeiras",
  "Pérola",
  "Barbosa Ferraz",
  "Uraí",
  "Primeiro de Maio",
  "Inácio Martins",
  "São Pedro do Ivaí",
  "São Jerônimo da Serra",
  "Jardim Alegre",
  "Mauá da Serra",
  "Missal",
  "Centenário do Sul",
  "Ribeirão Claro",
  "Nova Prata do Iguaçu",
  "Florestópolis",
  "Barracão",
  "Mariluz",
  "Catanduvas",
  "Nova Aurora",
  "São João",
  "Santa Tereza do Oeste",
  "Iretama",
  "São João do Ivaí",
  "Alto Piquiri",
  "Rondon",
  "Japurá",
  "Agudos do Sul",
  "Roncador",
  "Tunas do Paraná",
  "Santa Maria do Oeste",
  "São Jorge d'Oeste",
  "Douradina",
  "Congonhinhas",
  "Guamiranga",
  "São Sebastião da Amoreira",
  "Marilândia do Sul",
  "Califórnia",
  "Tuneiras do Oeste",
  "Santa Isabel do Ivaí",
  "Vera Cruz do Oeste",
  "Nova Santa Rosa",
  "Ivaté",
  "Jesuítas",
  "Reserva do Iguaçu",
  "Nova Fátima",
  "Campo do Tenente",
  "Tupãssi",
  "Cambira",
  "Santa Cruz de Monte Castelo",
  "Tomazina",
  "Icaraíma",
  "Figueira",
  "Guaraqueçaba",
  "Coronel Domingos Soares",
  "Boa Vista da Aparecida",
  "Quatiguá",
  "Antônio Olinto",
  "Paulo Frontin",
  "Abatiá",
  "Juranda",
  "Luiziana",
  "Bom Sucesso",
  "Verê",
  "Marilena",
  "Jussara",
  "Goioxim",
  "São Carlos do Ivaí",
  "Sabáudia",
  "Floresta",
  "Vitorino",
  "Renascença",
  "Sapopema",
  "Mariópolis",
  "Guairaçá",
  "Itambaracá",
  "Amaporã",
  "Ibema",
  "Formosa do Oeste",
  "Boa Ventura de São Roque",
  "Pinhalão",
  "Borrazópolis",
  "Pérola d'Oeste",
  "Perobal",
  "São José da Boa Vista",
  "Itambé",
  "Ouro Verde do Oeste",
  "Doutor Camargo",
  "Francisco Alves",
  "Paula Freitas",
  "Enéas Marques",
  "Nova Olímpia",
  "São João do Caiuá",
  "Adrianópolis",
  "São Tomé",
  "Pato Bragado",
  "São Pedro do Iguaçu",
  "Laranjal",
  "Mercedes",
  "Maria Helena",
  "Xambrê",
  "Saudade do Iguaçu",
  "Maripá",
  "Fernandes Pinheiro",
  "Guaraci",
  "São Jorge do Ivaí",
  "São Jorge do Patrocínio",
  "Doutor Ulysses",
  "Tapira",
  "Santo Inácio",
  "Presidente Castelo Branco",
  "Grandes Rios",
  "Braganey",
  "Jaboti",
  "Diamante d'Oeste",
  "Nova Tebas",
  "Tamboara",
  "Sertaneja",
  "Pranchita",
  "Honório Serpa",
  "Nova Esperança do Sudoeste",
  "Diamante do Norte",
  "Lupionópolis",
  "Janiópolis",
  "Japira",
  "Santana do Itararé",
  "Porto Amazonas",
  "Floraí",
  "Salto do Itararé",
  "Lobato",
  "Nova Cantu",
  "Fênix",
  "Lunardelli",
  "Marumbi",
  "Entre Rios do Oeste",
  "Rosário do Ivaí",
  "Flor da Serra do Sul",
  "Ramilândia",
  "Lindoeste",
  "Iguaraçu",
  "Indianópolis",
  "Foz do Jordão",
  "Serranópolis do Iguaçu",
  "Quinta do Sol",
  "Cruzeiro do Sul",
  "Itaguajé",
  "Quarto Centenário",
  "Nova Santa Bárbara",
  "Marquinho",
  "Planaltina do Paraná",
  "Cruzeiro do Iguaçu",
  "Rio Branco do Ivaí",
  "Porto Vitória",
  "Santa Mônica",
  "Virmond",
  "Quatro Pontes",
  "Munhoz de Mello",
  "Nossa Senhora das Graças",
  "Kaloré",
  "Boa Esperança",
  "Espigão Alto do Iguaçu",
  "Cafezal do Sul",
  "Leópolis",
  "Conselheiro Mairinck",
  "Atalaia",
  "Campina do Simão",
  "Prado Ferreira",
  "Santa Lúcia",
  "Guapirama",
  "Rancho Alegre",
  "Campo Bonito",
  "São José das Palmeiras",
  "Bom Jesus do Sul",
  "Nova América da Colina",
  "Ourizona",
  "Diamante do Sul",
  "Bela Vista da Caroba",
  "Salgado Filho",
  "Ivatuba",
  "Pitangueiras",
  "Paranapoema",
  "Santa Cecília do Pavão",
  "Jundiaí do Sul",
  "Bom Sucesso do Sul",
  "Santa Amélia",
  "Rio Bom",
  "Lidianópolis",
  "Mato Rico",
  "Porto Barreiro",
  "Inajá",
  "Corumbataí do Sul",
  "Farol",
  "Cafeara",
  "Arapuã",
  "Ângulo",
  "Cruzmaltina",
  "Sulina",
  "Godoy Moreira",
  "Novo Itacolomi",
  "Barra do Jacaré",
  "Anahy",
  "Pinhal de São Bento",
  "Flórida",
  "Itaúna do Sul",
  "Alto Paraíso",
  "Uniflor",
  "Santo Antônio do Caiuá",
  "Rancho Alegre d'Oeste",
  "Porto Rico",
  "Brasilândia do Sul",
  "Manfrinópolis",
  "Boa Esperança do Iguaçu",
  "São Pedro do Paraná",
  "Iguatu",
  "Guaporema",
  "Iracema do Oeste",
  "Mirador",
  "São Manoel do Paraná",
  "Santo Antônio do Paraíso",
  "Ariranha do Ivaí",
  "Miraselva",
  "Esperança Nova",
  "Santa Inês",
  "Nova Aliança do Ivaí",
  "Altamira do Paraná",
  "Jardim Olinda",
  "Recife",
  "Jaboatão dos Guararapes",
  "Petrolina",
  "Caruaru",
  "Olinda",
  "Paulista",
  "Cabo de Santo Agostinho",
  "Camaragibe",
  "Garanhuns",
  "Vitória de Santo Antão",
  "Igarassu",
  "São Lourenço da Mata",
  "Ipojuca",
  "Abreu e Lima",
  "Santa Cruz do Capibaribe",
  "Serra Talhada",
  "Gravatá",
  "Araripina",
  "Carpina",
  "Goiana",
  "Belo Jardim",
  "Arcoverde",
  "Ouricuri",
  "Escada",
  "Pesqueira",
  "Surubim",
  "Moreno",
  "Palmares",
  "Salgueiro",
  "Bezerros",
  "São Bento do Una",
  "Buíque",
  "Paudalho",
  "Limoeiro",
  "Timbaúba",
  "Brejo da Madre de Deus",
  "Bom Conselho",
  "Ribeirão",
  "Toritama",
  "Sirinhaém",
  "Águas Belas",
  "Catende",
  "Barreiros",
  "Santa Maria da Boa Vista",
  "Lajedo",
  "Bom Jardim",
  "Bodocó",
  "Aliança",
  "Bonito",
  "Custódia",
  "Afogados da Ingazeira",
  "São Caetano",
  "Água Preta",
  "Petrolândia",
  "Itambé",
  "Sertânia",
  "Cabrobó",
  "São José do Egito",
  "São José do Belmonte",
  "João Alfredo",
  "Floresta",
  "Vicência",
  "Nazaré da Mata",
  "Exu",
  "Gameleira",
  "Ipubi",
  "Trindade",
  "Glória do Goitá",
  "Ibimirim",
  "Taquaritinga do Norte",
  "Caetés",
  "Tabira",
  "Passira",
  "Tupanatinga",
  "Sanharó",
  "Pombos",
  "Itapissuma",
  "Ilha de Itamaracá",
  "Condado",
  "Tacaratu",
  "Panelas",
  "Quipapá",
  "Itaíba",
  "Lagoa Grande",
  "Macaparana",
  "Agrestina",
  "Canhotinho",
  "Cupira",
  "Inajá",
  "Orobó",
  "Tamandaré",
  "Rio Formoso",
  "São João",
  "Altinho",
  "Amaraji",
  "Pedra",
  "Flores",
  "Feira Nova",
  "Parnamirim",
  "Manari",
  "Chã Grande",
  "São José da Coroa Grande",
  "Lagoa de Itaenga",
  "São Joaquim do Monte",
  "Vertentes",
  "Araçoiaba",
  "Riacho das Almas",
  "Belém do São Francisco",
  "Cachoeirinha",
  "Capoeiras",
  "Afrânio",
  "Carnaíba",
  "Iati",
  "Dormentes",
  "Serrita",
  "Camocim de São Félix",
  "Venturosa",
  "Lagoa do Carro",
  "Correntes",
  "São Vicente Férrer",
  "Jataúba",
  "Itaquitinga",
  "Machados",
  "Lagoa dos Gatos",
  "São Benedito do Sul",
  "Joaquim Nabuco",
  "Saloá",
  "Santa Cruz",
  "Frei Miguelinho",
  "Mirandiba",
  "Jurema",
  "Orocó",
  "Triunfo",
  "Primavera",
  "Jupi",
  "Jatobá",
  "Alagoinha",
  "Xexéu",
  "Santa Filomena",
  "Barra de Guabiraba",
  "Casinhas",
  "Santa Maria do Cambucá",
  "Tracunhaém",
  "Chã de Alegria",
  "Itapetim",
  "Lagoa do Ouro",
  "Buenos Aires",
  "Carnaubeira da Penha",
  "Tacaimbó",
  "Betânia",
  "Santa Cruz da Baixa Verde",
  "Cortês",
  "Iguaracy",
  "Ferreiros",
  "Belém de Maria",
  "Cedro",
  "Santa Terezinha",
  "Jaqueira",
  "Paranatama",
  "Jucati",
  "Poção",
  "Angelim",
  "Moreilândia",
  "Salgadinho",
  "Maraial",
  "Calçado",
  "Terra Nova",
  "Sairé",
  "Verdejante",
  "Cumaru",
  "Brejão",
  "Camutanga",
  "Tuparetama",
  "Ibirajuba",
  "Granito",
  "Vertente do Lério",
  "Palmeirina",
  "Brejinho",
  "Terezinha",
  "Quixaba",
  "Solidão",
  "Calumbi",
  "Itacuruba",
  "Ingazeira",
  "Fernando de Noronha",
  "Teresina",
  "Parnaíba",
  "Picos",
  "Piripiri",
  "Floriano",
  "Barras",
  "Campo Maior",
  "União",
  "Altos",
  "Esperantina",
  "José de Freitas",
  "Pedro II",
  "Oeiras",
  "São Raimundo Nonato",
  "Miguel Alves",
  "Luís Correia",
  "Piracuruca",
  "Cocal",
  "Batalha",
  "Corrente",
  "Bom Jesus",
  "Luzilândia",
  "Uruçuí",
  "Canto do Buriti",
  "Valença do Piauí",
  "São João do Piauí",
  "Paulistana",
  "Buriti dos Lopes",
  "Castelo do Piauí",
  "Jaicós",
  "Pio IX",
  "Regeneração",
  "São Miguel do Tapuio",
  "Amarante",
  "Água Branca",
  "Inhuma",
  "Simões",
  "Palmeirais",
  "Elesbão Veloso",
  "Joaquim Pires",
  "Alto Longá",
  "São Pedro do Piauí",
  "Demerval Lobão",
  "Simplício Mendes",
  "Porto",
  "Pimenteiras",
  "Baixa Grande do Ribeiro",
  "Fronteiras",
  "Itainópolis",
  "Capitão de Campos",
  "Curimatá",
  "Avelino Lopes",
  "Itaueira",
  "Caracol",
  "Matias Olímpio",
  "Parnaguá",
  "Gilbués",
  "Cabeceiras do Piauí",
  "Monte Alegre do Piauí",
  "Monsenhor Gil",
  "Guadalupe",
  "Beneditinos",
  "Cristino Castro",
  "Sigefredo Pacheco",
  "Anísio de Abreu",
  "Ipiranga do Piauí",
  "Dom Inocêncio",
  "Ilha Grande",
  "Francisco Santos",
  "Murici dos Portelas",
  "Queimada Nova",
  "Redenção do Gurgueia",
  "Nossa Senhora dos Remédios",
  "Nazária",
  "Lagoa Alegre",
  "Marcolândia",
  "Isaías Coelho",
  "Madeiro",
  "Brasileira",
  "Cristalândia do Piauí",
  "Buriti dos Montes",
  "São João do Arraial",
  "Assunção do Piauí",
  "Monsenhor Hipólito",
  "Cajueiro da Praia",
  "Alagoinha do Piauí",
  "Colônia do Piauí",
  "Ribeiro Gonçalves",
  "Campo Largo do Piauí",
  "Nazaré do Piauí",
  "Acauã",
  "Dirceu Arcoverde",
  "Barro Duro",
  "Dom Expedito Lopes",
  "Padre Marcos",
  "Boa Hora",
  "Morro do Chapéu do Piauí",
  "Sussuapara",
  "Lagoa de São Francisco",
  "Angical do Piauí",
  "São José do Piauí",
  "Milton Brandão",
  "Novo Oriente do Piauí",
  "Colônia do Gurgueia",
  "Santo Antônio de Lisboa",
  "Massapê do Piauí",
  "Boqueirão do Piauí",
  "Rio Grande do Piauí",
  "Patos do Piauí",
  "São Francisco do Piauí",
  "São Julião",
  "Santa Filomena",
  "Santa Cruz do Piauí",
  "Betânia do Piauí",
  "Cocal dos Alves",
  "São João da Serra",
  "São João da Fronteira",
  "Campo Grande do Piauí",
  "Caraúbas do Piauí",
  "Santa Luz",
  "Aroazes",
  "São Francisco de Assis do Piauí",
  "Caldeirão Grande do Piauí",
  "Jacobina do Piauí",
  "Bonfim do Piauí",
  "Bom Princípio do Piauí",
  "Júlio Borges",
  "Campinas do Piauí",
  "Bertolínia",
  "Juazeiro do Piauí",
  "Joca Marques",
  "Caxingó",
  "Geminiano",
  "Alvorada do Gurgueia",
  "Curral Novo do Piauí",
  "São José do Divino",
  "Manoel Emídio",
  "Francinópolis",
  "Fartura do Piauí",
  "Landri Sales",
  "Santa Rosa do Piauí",
  "Lagoa do Sítio",
  "Agricolândia",
  "Caridade do Piauí",
  "Campo Alegre do Fidalgo",
  "São Gonçalo do Piauí",
  "Palmeira do Piauí",
  "Currais",
  "Eliseu Martins",
  "Várzea Branca",
  "Alegrete do Piauí",
  "Nossa Senhora de Nazaré",
  "Cocal de Telha",
  "Jatobá do Piauí",
  "São João da Varjota",
  "Conceição do Canindé",
  "Jurema",
  "Arraial",
  "Coronel José Dias",
  "Lagoa do Barro do Piauí",
  "Santana do Piauí",
  "São João da Canabrava",
  "São Lourenço do Piauí",
  "Guaribas",
  "Socorro do Piauí",
  "Marcos Parente",
  "Morro Cabeça no Tempo",
  "Jardim do Mulato",
  "Bocaina",
  "Ribeira do Piauí",
  "Wall Ferraz",
  "Curralinhos",
  "Flores do Piauí",
  "São Braz do Piauí",
  "Jerumenha",
  "Nova Santa Rita",
  "Várzea Grande",
  "Domingos Mourão",
  "Passagem Franca do Piauí",
  "Sebastião Leal",
  "Riacho Frio",
  "Francisco Ayres",
  "Capitão Gervásio Oliveira",
  "Paes Landim",
  "Lagoa do Piauí",
  "Pau d'Arco do Piauí",
  "Santa Cruz dos Milagres",
  "Bela Vista do Piauí",
  "Coivaras",
  "Barra d'Alcântara",
  "Canavieira",
  "Paquetá",
  "Hugo Napoleão",
  "Brejo do Piauí",
  "Santo Inácio do Piauí",
  "São José do Peixe",
  "Pavussu",
  "Belém do Piauí",
  "Cajazeiras do Piauí",
  "Sebastião Barros",
  "Pajeú do Piauí",
  "Barreiras do Piauí",
  "Francisco Macedo",
  "Antônio Almeida",
  "Prata do Piauí",
  "Vera Mendes",
  "São Gonçalo do Gurgueia",
  "São Miguel do Fidalgo",
  "Novo Santo Antônio",
  "João Costa",
  "Tamboril do Piauí",
  "Vila Nova do Piauí",
  "São Félix do Piauí",
  "Lagoinha do Piauí",
  "Tanque do Piauí",
  "Porto Alegre do Piauí",
  "São Luís do Piauí",
  "Floresta do Piauí",
  "Aroeiras do Itaim",
  "Pedro Laurentino",
  "Olho d'Água do Piauí",
  "São Miguel da Baixa Grande",
  "Santo Antônio dos Milagres",
  "Miguel Leão",
  "Rio de Janeiro",
  "São Gonçalo",
  "Duque de Caxias",
  "Nova Iguaçu",
  "Campos dos Goytacazes",
  "Belford Roxo",
  "Niterói",
  "São João de Meriti",
  "Petrópolis",
  "Volta Redonda",
  "Macaé",
  "Magé",
  "Itaboraí",
  "Cabo Frio",
  "Maricá",
  "Nova Friburgo",
  "Barra Mansa",
  "Angra dos Reis",
  "Mesquita",
  "Teresópolis",
  "Rio das Ostras",
  "Nilópolis",
  "Queimados",
  "Araruama",
  "Resende",
  "Itaguaí",
  "São Pedro da Aldeia",
  "Itaperuna",
  "Japeri",
  "Barra do Piraí",
  "Saquarema",
  "Seropédica",
  "Três Rios",
  "Valença",
  "Guapimirim",
  "Rio Bonito",
  "Cachoeiras de Macacu",
  "Paracambi",
  "Mangaratiba",
  "Casimiro de Abreu",
  "Paraíba do Sul",
  "Paraty",
  "Santo Antônio de Pádua",
  "São Francisco de Itabapoana",
  "São Fidélis",
  "Bom Jesus do Itabapoana",
  "Vassouras",
  "São João da Barra",
  "Armação dos Búzios",
  "Tanguá",
  "Itatiaia",
  "Arraial do Cabo",
  "Piraí",
  "Iguaba Grande",
  "Paty do Alferes",
  "Bom Jardim",
  "Miracema",
  "Miguel Pereira",
  "Pinheiral",
  "Quissamã",
  "Conceição de Macabu",
  "Itaocara",
  "Cordeiro",
  "São José do Vale do Rio Preto",
  "Silva Jardim",
  "Porto Real",
  "Cantagalo",
  "Carmo",
  "Porciúncula",
  "Mendes",
  "Rio Claro",
  "Sapucaia",
  "Carapebus",
  "Sumidouro",
  "Cambuci",
  "Italva",
  "Natividade",
  "Quatis",
  "Engenheiro Paulo de Frontin",
  "Cardoso Moreira",
  "Areal",
  "Aperibé",
  "Duas Barras",
  "Varre-Sai",
  "Trajano de Moraes",
  "Santa Maria Madalena",
  "São Sebastião do Alto",
  "Rio das Flores",
  "Comendador Levy Gasparian",
  "Laje do Muriaé",
  "São José de Ubá",
  "Macuco",
  "Natal",
  "Mossoró",
  "Parnamirim",
  "São Gonçalo do Amarante",
  "Macaíba",
  "Ceará-Mirim",
  "Caicó",
  "Assu",
  "Currais Novos",
  "São José de Mipibu",
  "Santa Cruz",
  "Nova Cruz",
  "Apodi",
  "João Câmara",
  "Canguaretama",
  "Touros",
  "Macau",
  "Pau dos Ferros",
  "Extremoz",
  "Baraúna",
  "Nísia Floresta",
  "Areia Branca",
  "Goianinha",
  "Santo Antônio",
  "São Miguel",
  "Monte Alegre",
  "Parelhas",
  "Caraúbas",
  "Jucurutu",
  "São Paulo do Potengi",
  "Guamaré",
  "Tangará",
  "Lagoa Nova",
  "Ipanguaçu",
  "Poço Branco",
  "Pendências",
  "Jardim de Piranhas",
  "Upanema",
  "Alto do Rodrigues",
  "Pedro Velho",
  "Tibau do Sul",
  "Arez",
  "Ielmo Marinho",
  "Passa-e-Fica",
  "Alexandria",
  "Governador Dix-Sept Rosado",
  "São José do Campestre",
  "Brejinho",
  "Patu",
  "Vera Cruz",
  "Maxaranguape",
  "Jardim do Seridó",
  "Taipu",
  "Serra do Mel",
  "Santana do Matos",
  "Angicos",
  "Lajes",
  "Campo Redondo",
  "Cerro Corá",
  "Montanhas",
  "Acari",
  "São Tomé",
  "Afonso Bezerra",
  "Carnaubais",
  "Rio do Fogo",
  "Tenente Ananias",
  "Serra Caiada",
  "Grossos",
  "Umarizal",
  "Espírito Santo",
  "São Miguel do Gostoso",
  "Boa Saúde",
  "Bom Jesus",
  "Luís Gomes",
  "Pureza",
  "Florânia",
  "Campo Grande",
  "Baía Formosa",
  "Jaçanã",
  "Martins",
  "Lagoa Salgada",
  "Marcelino Vieira",
  "Riachuelo",
  "Carnaúba dos Dantas",
  "São Rafael",
  "Serra Negra do Norte",
  "Cruzeta",
  "Portalegre",
  "Itajá",
  "Lagoa de Pedras",
  "Antônio Martins",
  "Doutor Severiano",
  "Jandaíra",
  "Lagoa d'Anta",
  "Porto do Mangue",
  "Pedro Avelino",
  "Caiçara do Norte",
  "São Vicente",
  "São João do Sabugi",
  "Senador Elói de Souza",
  "Serrinha",
  "Tenente Laurentino Cruz",
  "Equador",
  "Felipe Guerra",
  "José da Penha",
  "Itaú",
  "São Pedro",
  "Serra de São Bento",
  "Encanto",
  "Santa Maria",
  "Sítio Novo",
  "Bento Fernandes",
  "Várzea",
  "Coronel Ezequiel",
  "Parazinho",
  "Janduís",
  "Rafael Fernandes",
  "Japi",
  "Coronel João Pessoa",
  "Serrinha dos Pintos",
  "Ouro Branco",
  "Lajes Pintadas",
  "São José do Seridó",
  "Almino Afonso",
  "Messias Targino",
  "São Bento do Trairi",
  "Senador Georgino Avelino",
  "Rodolfo Fernandes",
  "Paraná",
  "São Francisco do Oeste",
  "Venha-Ver",
  "Olho-d'Água do Borges",
  "Riacho de Santana",
  "Tibau",
  "Major Sales",
  "Lucrécia",
  "Frutuoso Gomes",
  "Barcelona",
  "Jundiá",
  "Pilões",
  "Caiçara do Rio do Vento",
  "Paraú",
  "Riacho da Cruz",
  "São Fernando",
  "Ruy Barbosa",
  "Água Nova",
  "Vila Flor",
  "Rafael Godeiro",
  "Triunfo Potiguar",
  "Pedra Grande",
  "Passagem",
  "Fernando Pedroza",
  "Galinhos",
  "Francisco Dantas",
  "Lagoa de Velhos",
  "Santana do Seridó",
  "São Bento do Norte",
  "João Dias",
  "Taboleiro Grande",
  "Jardim de Angicos",
  "Timbaúba dos Batistas",
  "Pedra Preta",
  "Ipueira",
  "Bodó",
  "Monte das Gameleiras",
  "Severiano Melo",
  "Viçosa",
  "Porto Alegre",
  "Caxias do Sul",
  "Canoas",
  "Pelotas",
  "Santa Maria",
  "Gravataí",
  "Novo Hamburgo",
  "Viamão",
  "São Leopoldo",
  "Passo Fundo",
  "Rio Grande",
  "Alvorada",
  "Cachoeirinha",
  "Santa Cruz do Sul",
  "Sapucaia do Sul",
  "Bento Gonçalves",
  "Bagé",
  "Uruguaiana",
  "Erechim",
  "Guaíba",
  "Lajeado",
  "Ijuí",
  "Esteio",
  "Cachoeira do Sul",
  "Sapiranga",
  "Santo Ângelo",
  "Santana do Livramento",
  "Santa Rosa",
  "Farroupilha",
  "Alegrete",
  "Venâncio Aires",
  "Campo Bom",
  "Vacaria",
  "Camaquã",
  "Montenegro",
  "Carazinho",
  "São Gabriel",
  "São Borja",
  "Cruz Alta",
  "Parobé",
  "Taquara",
  "Canguçu",
  "Capão da Canoa",
  "Tramandaí",
  "Estância Velha",
  "Santiago",
  "Osório",
  "Canela",
  "Marau",
  "Panambi",
  "São Lourenço do Sul",
  "Santo Antônio da Patrulha",
  "Eldorado do Sul",
  "Charqueadas",
  "Torres",
  "Rosário do Sul",
  "Rio Pardo",
  "Dom Pedrito",
  "Portão",
  "Igrejinha",
  "Itaqui",
  "Gramado",
  "Garibaldi",
  "Estrela",
  "Teutônia",
  "Dois Irmãos",
  "Caçapava do Sul",
  "São Luiz Gonzaga",
  "Palmeira das Missões",
  "Frederico Westphalen",
  "Candelária",
  "Flores da Cunha",
  "Soledade",
  "Carlos Barbosa",
  "Nova Santa Rita",
  "Triunfo",
  "Santa Vitória do Palmar",
  "Três Coroas",
  "Nova Prata",
  "São José do Norte",
  "Lagoa Vermelha",
  "Vera Cruz",
  "Taquari",
  "Veranópolis",
  "Jaguarão",
  "Guaporé",
  "São Sebastião do Caí",
  "Encruzilhada do Sul",
  "Capão do Leão",
  "Ivoti",
  "Sarandi",
  "Tapejara",
  "São Jerônimo",
  "Tupanciretã",
  "Três de Maio",
  "Três Passos",
  "Imbé",
  "São Sepé",
  "Encantado",
  "Quaraí",
  "Nova Hartz",
  "São Francisco de Paula",
  "São Marcos",
  "Nova Petrópolis",
  "Rolante",
  "Arroio do Meio",
  "Butiá",
  "Piratini",
  "Ibirubá",
  "Horizontina",
  "Júlio de Castilhos",
  "Arroio Grande",
  "São Francisco de Assis",
  "Serafina Corrêa",
  "Não-Me-Toque",
  "Tapes",
  "Xangri-lá",
  "Cidreira",
  "Sananduva",
  "Agudo",
  "Getúlio Vargas",
  "São Pedro do Sul",
  "Giruá",
  "Restinga Sêca",
  "Espumoso",
  "Dom Feliciano",
  "Sobradinho",
  "Balneário Pinhal",
  "Bom Princípio",
  "Cerro Largo",
  "Arroio dos Ratos",
  "Santo Cristo",
  "Santo Augusto",
  "Feliz",
  "Barra do Ribeiro",
  "Arroio do Tigre",
  "Tenente Portela",
  "Crissiumal",
  "Antônio Prado",
  "Mostardas",
  "Cerro Grande do Sul",
  "Salto do Jacuí",
  "Cruzeiro do Sul",
  "Bom Retiro do Sul",
  "Cacequi",
  "Capela de Santana",
  "Pinheiro Machado",
  "Vale do Sol",
  "Redentora",
  "Nonoai",
  "Roca Sales",
  "Palmares do Sul",
  "Terra de Areia",
  "Bom Jesus",
  "Três Cachoeiras",
  "Barros Cassal",
  "Jaguari",
  "Seberi",
  "Ronda Alta",
  "Tapera",
  "Arroio do Sal",
  "Arvorezinha",
  "Fontoura Xavier",
  "Sinimbu",
  "Porto Xavier",
  "Nova Bassano",
  "Planalto",
  "Santo Antônio das Missões",
  "Constantina",
  "Candiota",
  "Chapada",
  "Casca",
  "Pantano Grande",
  "São Vicente do Sul",
  "Catuípe",
  "Jóia",
  "Paverama",
  "Caraá",
  "Entre-Ijuís",
  "General Câmara",
  "Glorinha",
  "Minas do Leão",
  "Cristal",
  "Santana da Boa Vista",
  "Salvador do Sul",
  "Santa Bárbara do Sul",
  "Paraí",
  "Tuparendi",
  "São Miguel das Missões",
  "Boqueirão do Leão",
  "Pedro Osório",
  "Paraíso do Sul",
  "Barão do Triunfo",
  "Segredo",
  "Lavras do Sul",
  "Ametista do Sul",
  "Guarani das Missões",
  "Manoel Viana",
  "Ibiraiaras",
  "Coronel Bicaco",
  "Amaral Ferrador",
  "Palmitinho",
  "Iraí",
  "Ajuricaba",
  "Ajuricaba",
  "Hulha Negra",
  "Chuí",
  "Herval",
  "Condor",
  "Santa Clara do Sul",
  "Roque Gonzales",
  "Maquiné",
  "Ipê",
  "Boa Vista do Buricá",
  "Erval Seco",
  "Faxinal do Soturno",
  "Barão de Cotegipe",
  "Passo do Sobrado",
  "Morro Redondo",
  "Sertão Santana",
  "Morro Reuter",
  "Formigueiro",
  "Augusto Pestana",
  "Nova Palma",
  "Lagoão",
  "Cambará do Sul",
  "Santa Maria do Herval",
  "Progresso",
  "Barão",
  "Lindolfo Collor",
  "Aratiba",
  "Bossoroca",
  "Cândido Godói",
  "Independência",
  "Vale Real",
  "Cerrito",
  "Anta Gorda",
  "Estação",
  "Alpestre",
  "Rodeio Bonito",
  "Araricá",
  "Passa-Sete",
  "Trindade do Sul",
  "Picada Café",
  "Alecrim",
  "São Paulo das Missões",
  "Sentinela do Sul",
  "Tucunduva",
  "Itaara",
  "Tiradentes do Sul",
  "Chuvisca",
  "Tavares",
  "Nova Esperança do Sul",
  "Gaurama",
  "Campinas do Sul",
  "Machadinho",
  "São Martinho",
  "Campina das Missões",
  "Barracão",
  "Sertão",
  "São Nicolau",
  "Brochier",
  "Selbach",
  "Liberato Salzano",
  "Cacique Doble",
  "Rondinha",
  "Tupandi",
  "Aceguá",
  "Harmonia",
  "Muçum",
  "Pinheirinho do Vale",
  "São José do Hortêncio",
  "Miraguaí",
  "Nova Araçá",
  "Tabaí",
  "Caibaté",
  "Capivari do Sul",
  "Erval Grande",
  "Mata",
  "David Canabarro",
  "Cerro Branco",
  "Humaitá",
  "Riozinho",
  "Ciríaco",
  "Ibiaçá",
  "Fazenda Vilanova",
  "Caiçara",
  "Viadutos",
  "Mato Leitão",
  "São João da Urtiga",
  "Tunas",
  "Maçambará",
  "Vicente Dutra",
  "Porto Lucena",
  "Ibarama",
  "Doutor Maurício Cardoso",
  "Gramado Xavier",
  "Vila Maria",
  "Pinhal Grande",
  "Vila Nova do Sul",
  "Campo Novo",
  "Maximiliano de Almeida",
  "Fortaleza dos Valos",
  "Novo Cabrais",
  "Marcelino Ramos",
  "Barra do Quaraí",
  "Três Palmeiras",
  "Novo Barreiro",
  "Ilópolis",
  "Ibirapuitã",
  "Marques de Souza",
  "Pontão",
  "Mariana Pimentel",
  "Pareci Novo",
  "São Pedro da Serra",
  "Putinga",
  "Pejuçara",
  "Cotiporã",
  "Quinze de Novembro",
  "Capão do Cipó",
  "Nova Roma do Sul",
  "Água Santa",
  "Jaboticaba",
  "Paim Filho",
  "Nova Alvorada",
  "Chiapetta",
  "Estrela Velha",
  "Jaquirana",
  "Severiano de Almeida",
  "São José dos Ausentes",
  "Arambaré",
  "Jacutinga",
  "Vale Verde",
  "Áurea",
  "Jari",
  "Itacurubi",
  "Dois Lajeados",
  "Turuçu",
  "Vila Flores",
  "Campestre da Serra",
  "Nova Bréscia",
  "Esmeralda",
  "Alegria",
  "Campos Borges",
  "Braga",
  "Barra do Guarita",
  "Monte Alegre dos Campos",
  "Caseiros",
  "Charrua",
  "São Martinho da Serra",
  "São Valentim",
  "Novo Machado",
  "Muitos Capões",
  "Ernestina",
  "Itatiba do Sul",
  "Mormaço",
  "Imigrante",
  "São Domingos do Sul",
  "Colorado",
  "Taquaruçu do Sul",
  "Tio Hugo",
  "Pinto Bandeira",
  "Vitória das Missões",
  "Westfália",
  "Alto Feliz",
  "Herveiras",
  "Dilermando de Aguiar",
  "Erebango",
  "Presidente Lucena",
  "Arroio do Padre",
  "Mampituba",
  "Dona Francisca",
  "São Pedro do Butiá",
  "Lagoa Bonita do Sul",
  "Morrinhos do Sul",
  "Sede Nova",
  "Centenário",
  "Vista Gaúcha",
  "Garruchos",
  "Esperança do Sul",
  "Cristal do Sul",
  "Victor Graeff",
  "São Jorge",
  "Quevedos",
  "Boa Vista do Sul",
  "Capitão",
  "Senador Salgado Filho",
  "Toropi",
  "Camargo",
  "Fagundes Varela",
  "Salvador das Missões",
  "São Valério do Sul",
  "Coxilha",
  "Vista Alegre",
  "Entre Rios do Sul",
  "Derrubadas",
  "Jacuizinho",
  "Maratá",
  "Nova Candelária",
  "Três Forquilhas",
  "Boa Vista do Incra",
  "Três Arroios",
  "Sagrada Família",
  "Saldanha Marinho",
  "Santa Margarida do Sul",
  "Pinhal",
  "Rio dos Índios",
  "Lajeado do Bugre",
  "Barra Funda",
  "Nova Pádua",
  "Mato Castelhano",
  "São João do Polêsine",
  "Coronel Barros",
  "Dom Pedro de Alcântara",
  "Monte Belo do Sul",
  "São José das Missões",
  "Boa Vista do Cadeado",
  "Colinas",
  "São José do Sul",
  "Forquetinha",
  "Itati",
  "Silveira Martins",
  "Porto Mauá",
  "Dezesseis de Novembro",
  "Travesseiro",
  "Eugênio de Castro",
  "Unistalda",
  "Paulo Bento",
  "São Vendelino",
  "Santo Expedito do Sul",
  "Cerro Grande",
  "Rolador",
  "Coqueiros do Sul",
  "Faxinalzinho",
  "São Valentim do Sul",
  "Inhacorá",
  "Pirapó",
  "Nova Ramada",
  "Novo Tiradentes",
  "Vanini",
  "Santo Antônio do Palma",
  "Poço das Antas",
  "Bozano",
  "Boa Vista das Missões",
  "Vila Lângaro",
  "Relvado",
  "São José do Inhacorá",
  "Itapuca",
  "Gramado dos Loureiros",
  "São Pedro das Missões",
  "Santo Antônio do Planalto",
  "Dois Irmãos das Missões",
  "Mariano Moro",
  "Doutor Ricardo",
  "Ubiretama",
  "Almirante Tamandaré do Sul",
  "Sete de Setembro",
  "Protásio Alves",
  "Pedras Altas",
  "Benjamin Constant do Sul",
  "São José do Herval",
  "Muliterno",
  "Pinhal da Serra",
  "Sério",
  "Ipiranga do Sul",
  "Quatro Irmãos",
  "Bom Progresso",
  "Ivorá",
  "Vespasiano Corrêa",
  "Cruzaltense",
  "Nova Boa Vista",
  "Linha Nova",
  "Santa Tereza",
  "Floriano Peixoto",
  "Novo Xingu",
  "Canudos do Vale",
  "Nicolau Vergueiro",
  "Santa Cecília do Sul",
  "Capão Bonito do Sul",
  "Barra do Rio Azul",
  "Gentil",
  "Mato Queimado",
  "Lagoa dos Três Cantos",
  "Coronel Pilar",
  "Alto Alegre",
  "Pouso Novo",
  "Vista Alegre do Prata",
  "Ponte Preta",
  "Coqueiro Baixo",
  "Guabiju",
  "Tupanci do Sul",
  "Montauri",
  "André da Rocha",
  "Carlos Gomes",
  "Porto Vera Cruz",
  "União da Serra",
  "Engenho Velho",
  "Porto Velho",
  "Ji-Paraná",
  "Ariquemes",
  "Vilhena",
  "Cacoal",
  "Rolim de Moura",
  "Jaru",
  "Guajará-Mirim",
  "Machadinho d'Oeste",
  "Buritis",
  "Pimenta Bueno",
  "Ouro Preto do Oeste",
  "Espigão d'Oeste",
  "Nova Mamoré",
  "Candeias do Jamari",
  "Cujubim",
  "São Miguel do Guaporé",
  "Alta Floresta d'Oeste",
  "Alto Paraíso",
  "São Francisco do Guaporé",
  "Nova Brasilândia d'Oeste",
  "Costa Marques",
  "Presidente Médici",
  "Monte Negro",
  "Cerejeiras",
  "Colorado do Oeste",
  "Campo Novo de Rondônia",
  "Alvorada d'Oeste",
  "Alto Alegre dos Parecis",
  "Seringueiras",
  "Chupinguaia",
  "Vale do Anari",
  "Urupá",
  "Itapuã do Oeste",
  "Mirante da Serra",
  "Theobroma",
  "Ministro Andreazza",
  "Novo Horizonte do Oeste",
  "Governador Jorge Teixeira",
  "Corumbiara",
  "Nova União",
  "Vale do Paraíso",
  "Parecis",
  "Cacaulândia",
  "Santa Luzia d'Oeste",
  "Cabixi",
  "São Felipe d'Oeste",
  "Teixeirópolis",
  "Rio Crespo",
  "Castanheiras",
  "Primavera de Rondônia",
  "Pimenteiras do Oeste",
  "Boa Vista",
  "Rorainópolis",
  "Caracaraí",
  "Pacaraima",
  "Cantá",
  "Mucajaí",
  "Alto Alegre",
  "Amajari",
  "Bonfim",
  "Iracema",
  "Normandia",
  "Uiramutã",
  "Caroebe",
  "São João da Baliza",
  "São Luís",
  "",
  "",
  "",
  "",
  "",
  "",
  "",
  "",
  "",
  "",
  "",
  "",
  "",
  "",
  "",
  "",
  "",
  "",
  "",
  "",
  "",
  "",
  "",
  "",
  "",
  "",
  "",
  "",
  "",
  "",
  "",
  "",
  "",
  "",
  "",
  "",
  "",
  "",
  "",
  "",
  "",
  "",
  "",
  "",
  "",
  "",
  "",
  "",
  "",
  "",
  "",
  "",
  "",
  "",
  "",
  "",
  "",
  "",
  "",
  "",
  "",
  "",
  "",
  "",
  "",
  "",
  "",
  "",
  "",
  "",
  "",
  "",
  "",
  "",
  "",
  "",
  "",
  "",
  "",
  "",
  "",
  "",
  "",
  "",
  "",
  "",
  "",
  "",
  "",
  "",
  "",
  "",
  "",
  "",
  "",
  "",
  "",
  "",
  "",
  "",
  "",
  "",
  "",
  "",
  "",
  "",
  "",
  "",
  "",
  "",
  "",
  "",
  "",
  "",
  "",
  "",
  "",
  "",
  "",
  "",
  "",
  "",
  "",
  "",
  "",
  "",
  "",
  "",
  "",
  "",
  "",
  "",
  "",
  "",
  "",
  "",
  "",
  "",
  "",
  "",
  "",
  "",
  "",
  "",
  "",
  "",
  "",
  "",
  "",
  "",
  "",
  "",
  "",
  "",
  "",
  "",
  "",
  "",
  "",
  "",
  "",
  "",
  "",
  "",
  "",
  "",
  "",
  "",
  "",
  "",
  "",
  "",
  "",
  "",
  "",
  "",
  "",
  "",
  "",
  "",
  "",
  "",
  "",
  "",
  "",
  "",
  "",
  "",
  "",
  "",
  "",
  "",
  "",
  "",
  "",
  "",
  "",
  "",
  "",
  "",
  "",
  "",
  "",
  "",
  "",
  "",
  "",
  "",
  "",
  "",
  "",
  "",
  "",
  "",
  "",
  "",
  "",
  "",
  "",
  "",
  "",
  "",
  "",
  "",
  "",
  "",
  "",
  "",
  "",
  "",
  "",
  "",
  "",
  "",
  "",
  "",
  "",
  "",
  "",
  "",
  "",
  "",
  "",
  "",
  "",
  "",
  "",
  "",
  "",
  "",
  "",
  "",
  "",
  "",
  "",
  "",
  "",
  "",
  "",
  "",
  "",
  "",
  "",
  "",
  "",
  "",
  "",
  "",
  "",
  "",
  "",
  "",
  "",
  "",
  "",
  "",
  "",
  "",
  "",
  "",
  "",
  "",
  "",
  "",
  "",
  "",
  "",
  "",
  "",
  "",
  "",
  "",
  "",
  "",
  "",
  "",
  "",
  "",
  "",
  "",
  "",
  "",
  "",
  "",
  "",
  "",
  "",
  "",
  "",
  "",
  "",
  "",
  "",
  "",
  "",
  "",
  "",
  "",
  "",
  "",
  "",
  "",
  "",
  "",
  "",
  "",
  "",
  "",
  "",
  "",
  "",
  "",
  "",
  "",
  "",
  "",
  "",
  "",
  "",
  "",
  "",
  "",
  "",
  "",
  "",
  "",
  "",
  "",
  "",
  "",
  "",
  "",
  "",
  "",
  "",
  "",
  "",
  "",
  "",
  "",
  "",
  "",
  "",
  "",
  "",
  "",
  "",
  "",
  "",
  "",
  "",
  "",
  "",
  "",
  "",
  "",
  "",
  "",
  "",
  "",
  "",
  "",
  "",
  "",
  "",
  "",
  "",
  "",
  "",
  "",
  "",
  "",
  "",
  "",
  "",
  "",
  "",
  "",
  "",
  "",
  "",
  "",
  "",
  "",
  "",
  "",
  "",
  "",
  "",
  "",
  "",
  "",
  "",
  "",
  "",
  "",
  "",
  "",
  "",
  "",
  "",
  "",
  "",
  "",
  "",
  "",
  "",
  "",
  "",
  "",
  "",
  "",
  "",
  "",
  "",
  "",
  "",
  "",
  "",
  "",
  "",
  "",
  "",
  "",
  "",
  "",
  "",
  "",
  "",
  "",
  "",
  "",
  "",
  "",
  "",
  "",
  "",
  "",
  "",
  "",
  "",
  "",
  "",
  "",
  "",
  "",
  "",
  "",
  "",
  "",
  "",
  "",
  "",
  "",
  "",
  "",
  "",
  "",
  "",
  "",
  "",
  "",
  "",
  "",
  "",
  "",
  "",
  "",
  "",
  "",
  "",
  "",
  "",
  "",
  "",
  "",
  "",
  "",
  "",
  "",
  "",
  "",
  "",
  "",
  "",
  "",
  "",
  "",
  "",
  "",
  "",
  "",
  "",
  "",
  "",
  "",
  "",
  "",
  "",
  "",
  "",
  "",
  "",
  "",
  "",
  "",
  "",
  "",
  "",
  "",
  "",
  "",
  "",
  "",
  "",
  "",
  "",
  "",
  "",
  "",
  "",
];

let sortedNames = cidades.sort();
let input = document.getElementById("input");
let text = document.getElementById("first-text");
let nameCity = document.getElementById("second-text");

input.addEventListener("keyup", (e) => {
  removeElements();
  for (let i of sortedNames) {

    if (
      i.toLowerCase().startsWith(input.value.toLowerCase()) &&
      input.value != ""
    ) {
      let listItem = document.createElement("li");
      listItem.classList.add("list-items");
      listItem.style.cursor = "pointer";
      listItem.setAttribute("onclick", "displayNames('" + i + "')");
      let word = "<b>" + i.substr(0, input.value.length) + "</b>";
      word += i.substr(input.value.length);
      listItem.innerHTML = word;
      document.querySelector(".list").appendChild(listItem);
      text.innerText = ""
      nameCity.innerText = ""
    }
  }
});
function displayNames(value) {
  input.value = value;
  text.innerText = "Você escolheu a cidade: "
  nameCity.innerText = input.value
  removeElements();
}

function removeElements() {
  let items = document.querySelectorAll(".list-items");
  items.forEach((item) => {
    item.remove();
  });
}
